guidance-guarantee-programme/telephone_appointment_planner

config/initializers/gds_sso.rb
We need to ensure that the FIRST user always has the resource_manager
permission, not just the user with the name "Test User".
=> Change strategy for auto-generating test user

config/initializers/gds_sso.rb, db/seeds.rb
This causes problems when migrating on a freshly minted database.
GDS-SSO's initializer is loaded thus the `User` creation is attempted
and fails since the schema is not yet in place.
=> Favour seeds over latent user creation

spec/features/resource_manager_manages_groups_spec.rb
We can use the one specified and mixed-in from the helper file.
=> Remove duplicate user authentication helper

db/seeds.rb, spec/factories/users.rb, spec/features/roles_spec.rb, spec/features/schedules_spec.rb, spec/models/user_spec.rb
We know guiders are users so no need for the `_user` suffix.
=> Remove redundant factory suffix

.travis.yml, Gemfile, Gemfile.lock
The other gem uses bitbucket for its CDN and hits the rate limits pretty
quickly and intermittently which is really nice when we're trying to get
our builds to run in CI.
=> Install `phantomjs` this way instead

Rakefile, lib/tasks/rubocop.rake
Rubocop is not loaded in environments other than development or test, so
we can't load the rake task.
=> Fix error where rails could not load on production

app/controllers/groups_controller.rb, app/forms/destroy_group_assignments.rb, app/views/groups/index.html.erb, config/routes.rb, spec/features/resource_manager_manages_guiders_spec.rb, spec/forms/destroy_group_assignments_spec.rb, spec/support/pages/manage_groups.rb
For the moment this leaves the actual group instances around.
=> Unassign guiders from groups

app/views/layouts/application.html.erb
The HTML5 History API is required for Turbolinks. This change checks if Turbolinks is being run in a supported browser and toggles the event we wait to boot the javascript with accordingly.
=> Toggle javascript 'ready' event based on Turbolinks support

Gemfile, Gemfile.lock
This works around a particularly nasty CVE in bundler that means source
resolution is non-deterministic when multiple gem sources exist.
See:
http://collectiveidea.com/blog/archives/2016/10/06/bundlers-multiple-source-security-vulnerability/
=> Lock dependencies per gem source

app/models/schedule.rb, spec/models/schedule_spec.rb
https://trello.com/c/GRqNIx44/116-guiders-cannot-have-more-than-one-schedule-starting-on-the-same-date
Also, slight refactor of schedules spec. Only review the second commit.
=> Ensure Schedule#start_at is unique per user

app/views/appointments/new.html.erb
- making calendar go full width
- personal details only in two columns
- improved vertical spacing between sections of form
=> Improving layout of new appointment page

app/controllers/schedules_controller.rb, app/models/schedule.rb, spec/features/resource_manager_manages_schedules_spec.rb, spec/support/pages/edit_schedule.rb, spec/support/pages/new_schedule.rb
This is because when we create a new schedule, we still want to be able
to edit that schedule today.
https://trello.com/c/GRqNIx44/116-guiders-cannot-have-more-than-one-schedule-starting-on-the-same-date
=> Schedule default start is (six weeks + one day)

app/assets/javascripts/calendars/appointment-availability.es6
- any guider availability count over 30 caused a JS error
and the event failed to render on the availibility calendar
=> Fix bug where guider availability > 30 caused an error

app/assets/javascripts/sortable-list.es6, app/helpers/multi_guider_helper.rb, app/views/users/index.html.erb
- this fixes an issue when you click the 'name' header for
the first time and it doesn't sort as the list is already
sorted A-Z in the DOM when it's initialised
- fixed a bug in the config for the sortable list
when there is no groups (trailing comma)
=> Force a sort on initialisation of sortable list

app/views/appointments/new.html.erb
- moved Year of birth to left column to even out form
=> Fix pension provider dropdown to work as a select2 dropdown

Gemfile, Gemfile.lock, app/models/appointment.rb, config/business_time.yml, config/initializers/business_time.rb, spec/factories/appointments.rb, spec/features/contact_centre_agent_creates_appointments_spec.rb, spec/models/appointment_spec.rb, spec/models/bookable_slot_spec.rb
Not taking into account bank holidays at the moment, which should be
worked on when we do the non-working-days feature.
This should abide by the rules mentioned here:
https://trello.com/c/XZoLbCJZ/119-appointment-booking-part-2
=> Appointments cannot be booked < 2 working days, > 30 working days

app/assets/javascripts/application.js, app/assets/javascripts/customer-age.es6, app/controllers/appointment_attempts_controller.rb, app/controllers/appointments_controller.rb, app/models/appointment_attempt.rb, app/views/appointment_attempts/ineligible.html.erb, app/views/appointment_attempts/new.html.erb, app/views/appointments/new.html.erb, app/views/layouts/application.html.erb, config/routes.rb, db/migrate/20161014111858_create_appointment_attempts.rb, db/schema.rb, spec/factories/appointment_attempts.rb, spec/features/contact_centre_agent_creates_appointments_spec.rb, spec/features/roles_spec.rb, spec/models/appointment_attempt_spec.rb, spec/support/pages/new_appointment.rb, spec/support/pages/new_appointment_attempt.rb
- Seperate page to take first_name, last_name, date_of_birth, and
defined_contribution_pension.
- If they are not eligible the agent is told.
- If they are then they can continue to book an appointment as usual.
(note that those fields are prefilled)
=> Customers can attempt an appointment and either be eligible or not

app/assets/javascripts/application.js, app/assets/javascripts/calendars/holidays.es6, app/controllers/holidays_controller.rb, app/jobs/generate_bank_holidays_job.rb, app/models/appointment.rb, app/models/bookable_slot.rb, app/models/holiday.rb, app/models/user.rb, app/serializers/holiday_serializer.rb, app/views/holidays/index.html.erb, app/views/layouts/application.html.erb, config/routes.rb, db/migrate/20161017130509_create_holidays.rb, db/schema.rb, db/seeds.rb, lib/tasks/jobs.rake, spec/factories/holidays.rb, spec/features/holidays_spec.rb, spec/features/roles_spec.rb, spec/models/appointment_spec.rb, spec/models/bookable_slot_spec.rb, spec/models/holiday_spec.rb, spec/support/pages/holidays.rb
- Add a link to /holidays in the nav
- Appointments don't get assigned to guiders on a holiday
- Don't show bookable slots if there's a holiday
- Seed bank holidays with ActiveJob
=> Resource managers can view holidays

app/views/appointments/new.html.erb, app/views/shared/_date_of_birth_form_field.html.erb
Before this, it was possible to provide an eligible date of birth
on the first page of the 'Book Appointment' journey, which is the
point at which the eligibility checks take place. However you
could then edit the date of birth to an ineligible age on the
second screen – resulting in an ineligible appointment being
successfully booked.
An unlikely scenario to occur, but this just prevents that from
happening.
=> Make date of birth readonly after eligiblity check

app/controllers/appointments_controller.rb, app/views/appointments/_personal_details_form.html.erb, app/views/appointments/edit.html.erb, app/views/appointments/new.html.erb, config/routes.rb, spec/factories/appointments.rb, spec/features/guider_edits_an_appointment_spec.rb, spec/support/pages/edit_appointment.rb
The guider can modify the personal details stored against appointments
assigned to them.
I extracted the common fields from new / edit into a partial to be
reused across both actions.
=> Allow guiders to edit their own appointments

app/assets/stylesheets/components/_calendars.scss
This was causing date range pickers to show on two lines, which means
the display area calculation was showing the range picker outside of the
scroll area.
=> Remove old unused style

app/controllers/appointments_controller.rb, app/helpers/appointment_helper.rb, app/models/appointment.rb, app/views/appointments/_personal_details_form.html.erb, app/views/appointments/edit.html.erb, db/migrate/20161021120409_add_status_to_appointments.rb, db/schema.rb, spec/features/contact_centre_agent_creates_appointments_spec.rb, spec/features/guider_edits_an_appointment_spec.rb, spec/models/appointment_spec.rb, spec/support/pages/edit_appointment.rb
- only available on edit appointment screen
- defaults to 'pending' on creation of an appointment
=> Adding a status to appointments

app/views/holidays/index.html.erb
This allows us to time travel successfully in our feature specs and ends
a whole class of spec bugs caused by @AndrewVos' incompetence.
=> Use server clock to set current date

spec/features/resource_manager_manages_holidays_spec.rb
We will be altering the way you can delete an appointment soon anyway, so a completely new spec will replace this.
=> Remove delete holiday spec as it's failing intermittently

app/models/bookable_slot.rb, app/models/schedule.rb, app/views/users/edit.html.erb, spec/factories/schedules.rb, spec/features/resource_manager_manages_schedules_spec.rb, spec/models/schedule_spec.rb, spec/support/pages/edit_user.rb, spec/support/pages/new_holiday.rb
- Schedules have no six week restrictions anymore
- Destroy all bookable slots when regenerating
- Bookable slots are still generated for six weeks
=> Remove six week restriction on schedules

.scss-lint.yml, .travis.yml, Gemfile, Gemfile.lock, app/assets/stylesheets/components/_guider-schedules.scss, config/environments/test.rb
This stops the intermittent timeouts caused when assets are compiled
upon request, during the first or subsequent JS spec runs.
=> Precompile when running in Travis CI

app/models/user.rb, spec/factories/bookable_slots.rb, spec/models/user_spec.rb
There was a really irritating issue where sometimes we just couldn't
book appointments, randomly. This was because the bookable slot that
matched didn't have an existing user anymore, because we deleted that
user in db:seed.
The fix is to ensure we delete any child bookable slots when we delete
users.
=> Fix orphaned bookable slots

app/assets/javascripts/date-range-picker.es6
- appears to be an issue with date range picker where it
passes 'false' through to moment js when there isn't a maxDate
specified
=> Fix moment JS warning on new holiday date picker

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/date-range-picker.es6, app/assets/stylesheets/vendor/_vendor.scss
- fixes issue where a maxDate attribute had to be specified
- now removed maxDate, now that it's no longer required
=> Update date range picker to latest version

app/models/bookable_slot.rb, spec/models/bookable_slot_spec.rb
Because of operator precedence we were dropping bookable slots for
users when the slots weren't actually covered by the holiday.
=> Fix BookableSlots#with_holidays negating valid slots

app/models/bookable_slot.rb, spec/models/bookable_slot_spec.rb
- if an appointment is cancelled then the bookable slot should be
bookable
=> Cancelled appointments are not considered for blocking bookable slots

Gemfile.lock
Ref: https://rubygems.org/gems/jsonapi-parser/versions/0.1.1.beta2
=> Bump `active_model_serializers` to avoid depending on yanked gem

app/assets/javascripts/application.js, app/assets/javascripts/calendars/guiders-appointments.es6, app/assets/stylesheets/components/_action-panel.scss, app/assets/stylesheets/components/_calendars.scss, app/controllers/appointments_controller.rb, app/controllers/guiders_controller.rb, app/controllers/resource_calendars_controller.rb, app/forms/batch_appointment_update.rb, app/models/appointment.rb, app/serializers/appointment_serializer.rb, app/serializers/user_serializer.rb, app/views/layouts/application.html.erb, app/views/resource_calendars/show.html.erb, config/routes.rb, db/schema.rb, spec/factories/appointments.rb, spec/features/resource_manager_modifies_appointments_spec.rb, spec/features/roles_spec.rb, spec/models/appointment_spec.rb, spec/support/pages/resource_calendar.rb
Adds the basis of the resource manager's appointments calendar. From here they
can currently move appointments around in terms of timing and the guider
carrying them out.
The commits just break things up a bit as there is a whole bunch of code here.
I'll squash things down after the review.
=> Resource manager appointments calendar

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/calendar.es6, app/views/appointments/new.html.erb, app/views/appointments/reschedule.html.erb, app/views/calendars/show.html.erb, app/views/holidays/index.html.erb, app/views/resource_calendars/show.html.erb, app/views/schedules/_form.html.erb
- Storing a cookie of the current view and date of each calendar
- Config for fullcalendar on initialisation gets overriden with values from cookie
- Remembers current defaultView/defaultDate settings for a year (across browser sessions)
=> Ensure that calendar stays on current view/date across page impressions

app/assets/javascripts/guider-schedules-chart.es6, app/views/users/edit.html.erb
- moved the chart away from the calendar folder as it's not
a class which inherits from calendar.es6
=> Renamed guiders-schedules to guider-schedule-chart

app/views/layouts/application.html.erb
We were running out of room a little bit.
Also adds a link to the resource manager calendar if applicable. The labels could probably be improved but it looks less broken for now.
=> Consolidate navigation into dropdown menus

app/controllers/appointment_attempts_controller.rb, spec/features/roles_spec.rb
Sometimes a guider will call the customer at the scheduled time,
and the customer is no longer available. Often the guider will
simply book another appointment for the customer at this stage.
There are other times that TPAS will want to book appointments in
the case that the customer has called through via a means other
than the contact centre.
=> Allow any user to book and reschedule appointments

app/models/appointment.rb, app/presenters/appointment_presenter.rb, app/views/appointments/search.html.erb, spec/features/agent_searches_for_appointments_spec.rb, spec/models/appointment_spec.rb
- ordering the search page by default by created_at
- when there is a search it orders by relevance
- added created_at as a column for clarity
=> Ensure that list js ordering of appointments in search works

app/assets/javascripts/calendars/guiders-appointments.es6
- Makes the calendar as large as the viewport
- Ensures that names of guiders remain on the screen as you scroll down
=> Sticky header for resource calendar

app/assets/javascripts/calendars/guiders-appointments.es6
- the resource calendar changes height to ensure we don't
get a scroll within a scroll situation. When the action
panel is displayed this could potentially obscure the
bottom of the calendar - this fixes that issue!
=> Ensure action panel doesn't overlay bottom of calendar

app/assets/javascripts/calendars/guiders-appointments.es6
- in the odd situation where there is an event without a guider
in the resource list this ensures that the calendar doesn't
break when in timeline mode
=> Ensure calendar doesn't break when guider for an event doesn't exist

app/assets/javascripts/calendars/guiders-appointments.es6, app/assets/stylesheets/components/_calendars.scss, app/assets/stylesheets/lib/_colours.scss, app/models/appointment.rb, app/serializers/appointment_serializer.rb
- cancelled appointments are now red (and transparent)
- moved appointments are now altered to be green
=> Showing cancelled appointments on the resource calendar

db/migrate/20161103134203_bump_appointments_id.rb, db/schema.rb
This reverts commit 4e241309baac877c2795000fedb4fc4b4a10e60d.
This won't work under dbs that have been schema loaded.
=> Revert "Start appointments id at 100,000"

app/forms/batch_appointment_update.rb
We didn't need to tap into the appointment, `.update` has the same
semantics.
=> Simplify appointment update

.travis.yml, app/models/slot.rb
This should resolve the intermittent test failures (the latest ones, at
least) in the CI environment. It seems the specs assert on the
particular ordering of `Schedule#slots` but the order was not
guaranteed.
I added a default scope as it's easiest and it seemed to make sense to
order slots in a schedule by their ordinal day of week.
=> Return slots deterministically

app/controllers/appointments_controller.rb, app/forms/batch_appointment_update.rb, app/mailers/appointment_mailer.rb, spec/mailers/appointment_mailer_spec.rb
The postfix statement modifier was following the mailer calls around
like a bad smell.
=> Guard against the absence of a customer email

app/jobs/pusher_notification_job.rb, spec/jobs/pusher_notification_job_spec.rb
Limits the guider notifications to the same day otherwise the guider
may be overwhelmed by notifications and do a frighten.
=> Push notify for appointments on the same day

app/controllers/activities_controller.rb, app/models/activity.rb, app/models/appointment.rb, app/models/assignment_activity.rb, app/models/audit_activity.rb, app/models/create_activity.rb, app/views/activities/_activity_feed.html.erb, app/views/activities/_assignment_activity.html.erb, app/views/activities/_audit_activity.html.erb, app/views/activities/_create_activity.html.erb, app/views/activities/_message_activity.html.erb, db/migrate/20161107140328_add_prior_owner_id_to_activities.rb, db/migrate/20161107141610_add_owner_to_activities.rb, db/schema.rb, spec/factories/activities.rb, spec/factories/appointments.rb, spec/features/user_views_booking_activities_spec.rb, spec/models/activity_spec.rb, spec/models/assignment_activity_spec.rb, spec/models/audit_activity_spec.rb, spec/models/create_activity_spec.rb
I'm tempted to introduce an additional STI called `ReassignmentActivity` to simplify things.
Also, notice that `Activity` now has `owner` and `prior_owner`. They will be used to query activities when we have a per-user activity-feed.
=> Add assigned and reassigned activities to appointments

app/views/appointments/edit.html.erb, app/views/appointments/new.html.erb, app/views/appointments/reschedule.html.erb, app/views/appointments/search.html.erb, app/views/calendars/show.html.erb, app/views/company_calendars/show.html.erb, app/views/groups/index.html.erb, app/views/holidays/edit.html.erb, app/views/holidays/index.html.erb, app/views/holidays/new.html.erb, app/views/reports/new.html.erb, app/views/resource_calendars/show.html.erb, app/views/schedules/edit.html.erb, app/views/schedules/new.html.erb, app/views/users/edit.html.erb, app/views/users/index.html.erb
Kills the H1 on the resource calendar page and moves breadcrumbs (on all pages) out of the `page-header`, which buys us quite a bit more vertical spacing.
**Before:**
**After:**
=> Reduce vertical spacing

app/assets/javascripts/calendars/guiders-appointments.es6
Previously they were a little terse and fullcalendar-specific, and
TPAS are familiar with the 'Vertical' and 'Horizontal' naming.
=> More descriptive button labels on the resource calendar

app/models/schedule.rb
Since removing the 6 week window restrictions around creating
and modifying schedules, the previous default start date no
longer made sense.
=> Make default new schedule start date 'today'

app/controllers/appointments_controller.rb, app/jobs/pusher_notification_job.rb, app/lib/batch_appointment_update.rb, app/lib/notifier.rb, spec/features/guider_edits_an_appointment_spec.rb, spec/jobs/pusher_notification_job_spec.rb
Notifies on more appointment scenarios. For now we just display the typical
push notification modal for changes made to appointments during 'today'.
=> Notify on appointment alterations

spec/features/agent_manages_appointments_spec.rb, spec/features/guider_edits_an_appointment_spec.rb, spec/features/resource_manager_modifies_appointments_spec.rb, spec/rails_helper.rb
Including the Active Job test helpers stops jobs being performed inline
unless scoped within the `perform_enqueued_jobs` helper. By not mixing
this into our feature specs we can implicitly dequeue jobs inline.
=> Dequeue jobs inline by default

app/assets/javascripts/calendars/guiders-appointments.es6, app/controllers/appointments_controller.rb, app/serializers/appointment_serializer.rb, spec/features/guider_views_appointments_spec.rb, spec/features/resource_manager_modifies_appointments_spec.rb
- if they move/resize an appointment then they are warned
they are going to lose changes if they then try and navigate
away
- enable links through to edit appointment page for events
on resource manager calendar and company calendar for a guider
=> Alerts the resource manager that they are about to lose changes

app/assets/javascripts/calendars/guider-appointments.es6, app/controllers/appointments_controller.rb, spec/factories/users.rb, spec/features/guider_views_appointments_spec.rb, spec/support/user_helpers.rb
When the user is both a resource manager and a guider - the scoping logic
for the appointments JSON would short-circuit to all appointments due to
ordering of conditionals favouring the resource manager permission.
This change ensures that when the user is both guider and manager they only
see appointments scoped directly to them - i.e. appointments they are
holding with the customer.
=> Display only my appointments

.gitignore, Gemfile, Gemfile.lock, spec/rails_helper.rb
This is fairly invasive so by default we opt-out of coverage in normal
usage. Obviously you can still `TRAVIS=true rspec` if you care.
=> Check for test coverage in CI

app/assets/javascripts/calendars/guiders-appointments.es6, app/assets/stylesheets/components/_calendars.scss
To help resource managers know they're dragging and dropping
events into the correct areas.
=> Highlight the currently 'dragged-over' resource and time

app/assets/javascripts/calendars/guider-appointments.es6, app/assets/javascripts/calendars/guiders-appointments.es6, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_calendars.scss, app/assets/stylesheets/components/_guider-schedules.scss, app/assets/stylesheets/lib/_colours.scss, app/assets/stylesheets/lib/_striped_background.scss
- attempted to make appointments stand out and make the calendar
not so overwhelming with colour
- cancelled appointments now have the same hue as default appointment
colour - so to not stand out too much
- holidays are now grey, so not to confuse with cancelled appointments
=> Calendar colours

app/assets/stylesheets/components/_calendars.scss
Before the 'now' line was overruling this, and it was falling
behind background events.
As we've over the top of everything now this also knocks back
the colour to be slightly transparent.
=> Ensure the z-index is high enough for the highlight line

app/assets/javascripts/calendars/allocations.es6
We were trying to calculate position of elements that didn't exist.
E.g. dragging an event to before 8.30am or after 7pm.
Also adjusts the 'boot' order to ensure `this.$el` is defined
before we add the row highlighter.
=> Ensure there's a corresponding time being dragged to

app/controllers/home_controller.rb, spec/features/custom_role_redirects_spec.rb
Seems to be a more frequently used page than the groups management.
=> Make resource calendar the homepage for resource managers

app/assets/javascripts/calendar.es6, app/assets/javascripts/calendars/allocations.es6, app/controllers/appointments_controller.rb, app/views/resource_calendars/show.html.erb, spec/features/resource_manager_modifies_appointments_spec.rb, spec/support/pages/resource_calendar.rb
- Store event changes with XHR
- Ensures that resource calendar always defaults to today
when returning back to the calendar
- Ensures that the company calendar is unaffected by this
change
=> Disable cookie config saving when using resource calendar

app/assets/javascripts/calendars/guider-slot-picker.es6, app/assets/stylesheets/components/_calendars.scss, app/assets/stylesheets/lib/_colours.scss
Not sure about this colour but it sets up its own variable
for easy tweaking in the future.
Before:
Now:
=> Make schedule edit screen less painful on the eyes

.rubocop.yml, spec/features/agent_manages_appointments_spec.rb, spec/features/guider_edits_an_appointment_spec.rb, spec/features/guider_views_appointments_spec.rb, spec/features/resource_manager_downloads_appointment_reports_spec.rb, spec/features/resource_manager_downloads_utilisation_reports_spec.rb, spec/features/resource_manager_manages_guiders_spec.rb, spec/features/resource_manager_manages_holidays_spec.rb, spec/features/resource_manager_manages_schedules_spec.rb, spec/features/resource_manager_modifies_appointments_spec.rb
This is a useless check for the feature specs and it makes sense to
remove the individual enabling / disabling in favour of globally
disabling the cop for features.
=> Disable ABC size cop for features

spec/models/appointment_spec.rb
We were getting failures because the appointments factory generates
random names and sometimes either the first name or the last name was
not distinct.
=> Fix flaky sull text search test

app/assets/javascripts/calendars/company.es6, app/views/layouts/application.html.erb, app/views/users/sort.html.erb
- Rename `Availability` to `Guiders`
=> Add link in nav to "Sort guiders"

app/assets/javascripts/calendars/guider-appointments.es6
Makes it easier to view the day at a glance.
Bit like this:
=> Add 'list' view to guider's appointments page

app/assets/stylesheets/components/_calendars.scss
When bookable slots starting after a holiday's start time, they would appear over the top of the holiday. This resulted in the guider appearing to be available when they were in fact not.
**See example below for a holiday that ends at 14:00, but appears to end earlier**
Before:
After:
=> Ensure holidays appear over the top of bookable slots

spec/features/user_rebooks_appointments_spec.rb
This was my fault – should've rebased before merging #244 
(because #247 had been merged in the interim)
=> Remove unnecessary disabling of Metrics/MethodLength.

app/assets/stylesheets/components/_alert.scss, app/views/resource_calendars/show.html.erb
As we use AJAX-style saving on this calendar, it makes sense to
flash the message and then fade it out. But on other pages
this just looks a little strange, so they get the standard
full width, block style message.
This essentially fixes the following:
with:
=> Only use the floating 'fixed' flash message style on allocations

app/views/users/index.html.erb
Seems the groups are carrying the weight of the content on this
page, so this gives them a little more space.
Before:
After:
=> Balance column widths on guider list page

app/lib/mailgun_headers.rb, app/mailers/application_mailer.rb, app/mailers/appointment_mailer.rb, spec/mailers/appointment_mailer_spec.rb
Adds mailgun specific headers for identification.
Changes the `from` address so we're unique from planner and other apps we
send email from.
=> Configure mailers

app/assets/stylesheets/components/_calendars.scss
We need to be quite specific to override FullCalendar's styles.
Before:
After:
=> Ensure our calendar styles apply to month views

app/assets/javascripts/calendars/guider-slot-picker.es6
- when you remove a slot and there are no events to render
the check on whether to set the unload event no longer happens.
This caters for that scenario
=> Fixes issue with slot picker and the unload event

app/assets/javascripts/calendar.es6
As we're dealing with quite small columns, the events display
a little odd.
More information here: https://fullcalendar.io/docs/agenda/slotEventOverlap/
=> When events overlap, make their widths more even

app/controllers/mail_gun/drops_controller.rb, app/forms/drop_form.rb, app/lib/mailgun_headers.rb, app/mailers/appointment_mailer.rb, app/models/drop_activity.rb, app/views/activities/_drop_activity.html.erb, config/routes.rb, spec/forms/drop_form_spec.rb, spec/mailers/appointment_mailer_spec.rb, spec/models/drop_activity_spec.rb, spec/requests/mailgun_drop_notification_spec.rb
Exposes a webhook end point to process delivery of mailgun drop / bounce
notifications. The 'owner' is the appointment's associated guider. We may
want to revisit this later.
=> Process mailgun drop notifications as activities

app/assets/javascripts/modules/calendars/guider-slot-picker.es6
- Fix bug where removing a slot on the slot picker, removed all of them
- Fix bug where removing a slot didn't result in the unload event being trigged and a warning message popping up
=> Fix slot picker bugs

app/controllers/appointments_controller.rb, app/models/appointment.rb
Moves the copying to `Appointment` and golfs down the resulting code a
little bit.
=> Make copying an appointment's responsibility

app/assets/javascripts/modules/calendars/guider-slot-picker.es6
- saving unix timestamps was causing an issue in IE11 where
date matching was an hour out (timezone issue possibly?)
- replaced unix timestamps in favour of date strings
- fixed another issue where IE11 was alerting multiple times
=> Fix IE11 issue with unload event on slot picker edit page

app/models/audit_activity.rb, spec/models/audit_activity_spec.rb
=> Don't show an audit activity if only the guider was updated

app/assets/javascripts/modules/calendar.es6, app/assets/javascripts/modules/calendars/company.es6, app/assets/stylesheets/application.scss, app/assets/stylesheets/helper/_bootstrap_overrides.scss, app/views/activities/_activity_feed.html.erb, app/views/schedules/_form.html.erb, app/views/shared/_calendar_filter.html.erb, app/views/shared/_date_of_birth_form_field.html.erb, app/views/users/index.html.erb
- Ensuring form elements have labels
- Ensuring there is enough colour contrast on the breadcrumb
- Just hide the contents of the events on the resource calendar
from visual users, rather than removing it
- Ensuring that icon buttons on full calendar have
hidden screen reader text alternatives
=> Accessibility fixes

app/controllers/activities_controller.rb, app/controllers/application_controller.rb, app/controllers/appointments_controller.rb, app/controllers/company_calendars_controller.rb, app/controllers/my_appointments_controller.rb, app/helpers/breadcrumb_helper.rb, app/views/appointments/edit.html.erb, spec/features/breadcrumb_spec.rb, spec/support/pages/edit_appointment.rb
Also, change the way that we store the previous page so that we can
always show the correct breadcrumb on appointments#edit.
=> Rerender edit page after editing an appointment

config/environments/production.rb
Force cookies and stuff over SSL. Also ensures we use STS.
=> Force SSL in production-like environments

app/views/activities/_activity.html.erb, app/views/activities/index.html.erb
On the edit page, each activity was a link back to the same page - this is not great for screen reader users, when they view the list of available links on the page.
=> Only link activity feed items from my activity page

app/assets/javascripts/modules/customer-age.es6, app/views/shared/_date_of_birth_form_field.html.erb
Makes the date of birth components required (client-side) plus:
Checks:
- the year is numeric, starts with 19 and is 4 digits
- the month is numeric, between 01-12 and max 2 digits
- the day is numeric, between 01-31 and max 2 digits
The only catch is that I'm not certain this kicks up the numeric keyboard on mobile devices.
=> Better validation for date of birth components

db/migrate/20161004141342_break_apart_slots_start_and_end.rb
This was borked as a `default_scope` on `Slot` was adding ordering by a
column that doesn't exist at this particular point in time.
=> Fix broken migration

.travis.yml
So we're always sure that our migrations work after a drop.
=> Use db:migrate instead of db:schema:load in CI

app/views/layouts/application.html.erb
**Before**
**After**
- move my/company appointments to appointments menu
=> Re-order items in navigation to stop it wrapping

lib/tasks/js.rake
I'm using [yarn](yarnpkg.com) locally, so allow for running `yarn run` if it exists, but falling back to `npm run`
=> Run js:lint using yarn where possible

app/controllers/appointments_controller.rb, app/views/appointments/_availability_calendar.html.erb, app/views/appointments/_unable_to_assign.html.erb, app/views/appointments/new.html.erb, app/views/appointments/reschedule.html.erb
**Fix typo in error message**
**Before**
**After**
**Reduce duplication across 'new' and 'reschedule' appointments**
=> Improve view templates for scheduling an appointment

app/assets/stylesheets/components/_activity.scss, app/views/activities/_activity.html.erb
**Before**
**After**
- Activity items with a large amount of text wrapped awkardly
- This fixes this issue by laying out an individual activity feed
item into seperate columns
=> Improve text wrapping on activity feed items

app/assets/javascripts/modules/quick-search.es6, app/assets/stylesheets/components/_action-buttons.scss, app/assets/stylesheets/components/_quick-search.scss, app/controllers/appointments_controller.rb, app/views/appointments/edit.html.erb, app/views/appointments/search.html.erb, app/views/layouts/application.html.erb, app/views/shared/_navigation.html.erb, spec/features/agent_searches_for_appointments_spec.rb, spec/support/pages/search.rb
- Altered search to redirect to an appointment edit page
if it's the only result returned
- Added quick search form in the site navigation which
submits directly to the appointment search page
- Added reschedule and rebook buttons to appointment edit
page, so search results page isn't the only place to access
these actions
=> Adding 'quick search' functionality

spec/rails_helper.rb, spec/support/pages/activities.rb, spec/support/pages/allocations.rb, spec/support/pages/base.rb, spec/support/pages/company_calendar.rb, spec/support/pages/edit_appointment.rb, spec/support/pages/edit_holiday.rb, spec/support/pages/edit_schedule.rb, spec/support/pages/edit_user.rb, spec/support/pages/holidays.rb, spec/support/pages/home.rb, spec/support/pages/manage_groups.rb, spec/support/pages/manage_guiders.rb, spec/support/pages/my_appointments.rb, spec/support/pages/new_appointment.rb, spec/support/pages/new_appointment_report.rb, spec/support/pages/new_holiday.rb, spec/support/pages/new_schedule.rb, spec/support/pages/new_utilisation_report.rb, spec/support/pages/report_csv.rb, spec/support/pages/reschedule_appointment.rb, spec/support/pages/search.rb, spec/support/pages/sort_guiders.rb, spec/support/pages/users.rb
This removes a bunch of duplication when requiring the authorisation
error message assertions. I made all the pages derive from the common
base class for consistency, whether they use this element or not.
I've had to explicitly require the base file in the spec helper since
the 'autoloading' glob loads the spec/support files in alphabetical
order, causing problems with load ordering on the pages that begin 'a*'.
=> Move error element to page base class

Gemfile, Gemfile.lock
We can use the released version now they've cut a gem with our latest
changes.
=> Switch back to released GDS-SSO

spec/features/resource_manager_modifies_appointments_spec.rb
This spec was failing during the weekends due to its dependency on
working days.
=> Fix date-sensitive spec

Gemfile, Gemfile.lock, config/environments/production.rb
Lets us log in a single-line format that doesn't get interleaved,
similar to the heroku router logs.
This will affect production-like environments, not development or test.
Example:
`method=GET path=/bookable_slots format=json controller=BookableSlotsController action=index status=200 duration=341.05 view=211.14 db=70.21`
=> Reduce logging noise with lograge

.travis.yml
In theory, using the lesser-used trusty distribution routing should
reduce time spent in the build queue. This won't have any further,
noticeable effect on our test runs.
=> Reduce build queue times

app/assets/stylesheets/components/_quick-search.scss, app/views/shared/_navigation.html.erb
- using bootstrap classes for form input
=> Improve look of quick-search across different browsers

spec/support/poltergeist.rb
We don't need to wait so long when the specs fail to find elements that
appear via JS. We still do in travis however.
=> Don't wait so long for failing JS specs

app/assets/javascripts/modules/calendar.es6, app/assets/javascripts/modules/sortable_guiders.es6, app/assets/javascripts/tap-base.es6, app/views/users/sort.html.erb, spec/support/pages/sort_guiders.rb
- Add an action panel with the save button when ordering is changed
- If there has been a change in the ordering it sets the unload
event to warn users about navigating away without saving changes
=> Stop users from losing changes to sortable guiders

app/assets/javascripts/modules/calendars/allocations.es6, app/assets/javascripts/modules/calendars/guider-slot-picker.es6, app/assets/javascripts/modules/sortable_guiders.es6, app/assets/javascripts/tap-base.es6
- removed window.unload event as beforeunload is enough
to work in Chrome/Firefox/IE11
- moved clear and set unload methods into TapBase
=> Stop multiple unload event alerts on allocations calendar

app/views/layouts/application.html.erb
Requires `BUGMUNCHER_KEY` to be an environment variable.
This is part of the change to show BugMuncher across all relevant environments, including production as we would like to get direct feedback from the users at TP and TPAS.
=> Show BugMuncher on all environments and use environment variable

app/controllers/appointments_controller.rb, spec/features/guider_edits_an_appointment_spec.rb, spec/support/pages/edit_appointment.rb
We shouldn't be rendering the edit action after a successful update
Instead we should be following the POST / redirect / GET rule.
Consequently this means the expected flash message is displayed again.
=> Restore missing flash message

app/views/appointments/_personal_details_form.html.erb, app/views/appointments/edit.html.erb, spec/features/guider_edits_an_appointment_spec.rb, spec/support/pages/edit_appointment.rb
- Displays appointment created date, appointment date/time
and the current guider it is assigned to
=> Show booking details on the edit appointment page

app/views/activities/index.html.erb, spec/features/guider_views_their_activities_spec.rb, spec/support/pages/activities.rb
- Previously if there was no activity, the page was looking rather
empty
=> Display a message if there is no activity on the 'My activity' page

app/views/shared/_date_of_birth_form_field.html.erb
The regular expression was be interpreted incorrectly on IE,
which was stopping TPAS or TP being able to book appointments
with certain birth dates.
So as long as we're checking for a numeric input then this should
suffice.
=> Relax client side valiation on date of birth fields

app/assets/javascripts/modules/search-highlight.es6, app/assets/stylesheets/helper/_bootstrap_overrides.scss, app/models/appointment_search.rb, app/views/appointments/search.html.erb
- allow certain columns of the search results to
have part of its contents replaced with a <mark>
element to highlight a match
=> Highlight search term in Javascript

app/views/shared/_navigation.html.erb
- Renamed to 'Holidays' to be consistant with H1 on page
=> Rename 'Holidays & Unavailability' in navigation

app/assets/javascripts/modules/calendars/allocations.es6
I'm not sure is 100% what the acceptance criteria mentioned, but might be better?
=> Disallow creating holidays that overlap other holidays from allocations

db/seeds.rb
Appointments were failing to be assigned to guiders because we were
using appointments that were obscured by holidays.
=> Fix broken appointment seeding

app/assets/stylesheets/components/_action-buttons.scss
=> Ensure the action buttons on edit appointment page don't wrap

app/views/appointment_reports/new.html.erb, app/views/utilisation_reports/new.html.erb
**Before**
**After**
- Placed form controls into grid columns, so that
dropdowns don't go full width on desktop size viewports
=> Improve layout for report forms

app/views/schedules/_form.html.erb
**Before**
**After**
- to be consistent with other forms on the app
=> Altered schedule edit/new save button to be primary button

app/views/appointment_reports/new.html.erb, app/views/appointments/search.html.erb, app/views/utilisation_reports/new.html.erb
- When you select a date range it's nicer to close the date
input dialog automatically so you can complete the form quicker
=> Add autoApply: true to any date pickers without time selection

app/assets/stylesheets/components/_sortable-guiders.scss, app/views/users/sort.html.erb
I would show a screenshot, but it's proving tricky to screenshot with the right cursor on the screen!!
=> Alter cursor to 'move' icon when hovering over sortable guiders

app/assets/javascripts/modules/calendar.es6, app/assets/javascripts/modules/calendars/appointment-availability.es6, app/assets/stylesheets/components/_calendars.scss
- on slow network connections it will be more obvious
to the user that something is happening when they
change the current view of the calendar
=> Add a loading indicator to the calendars

app/assets/javascripts/modules/calendars/allocations.es6, app/assets/javascripts/modules/calendars/appointment-availability.es6, app/assets/javascripts/modules/guiders-multi-action.es6, app/assets/javascripts/modules/multi-checkbox.es6, app/views/allocations/show.html.erb, app/views/appointments/_availability_calendar.html.erb, app/views/shared/_date_of_birth_form_field.html.erb, app/views/users/index.html.erb
- GOVUK Admin standard is to use classes with .js- prefix
https://github.com/alphagov/govuk_admin_template/blob/master/JAVASCRIPT.md
- altered any finding of DOM elements with $('[data-X]') to
$('.js-X') to be consistent
=> Altered way jquery finds DOM elements across different modules

app/lib/appointment_importer.rb, spec/features/pension_wise_imports_historical_data_spec.rb
This massively speeds up the import process plus it stops pusher
notifications being triggered unnecessarily during import.
=> Don't create activities when importing

app/assets/javascripts/modules/calendars/my-appointments.es6, app/assets/stylesheets/components/_calendars.scss
- forcing visited link colour for the list view to be black and
not purple, which is hard to see on the cancelled event bg
=> Adding a (C) after the text of an appointment in 'my appointments'

app/views/appointment_mailer/updated.html.erb, app/views/appointment_mailer/updated.text.erb, spec/mailers/appointment_mailer_spec.rb
Although we have 70 minute appointments in the database, the customer's
appointment is only 45 minutes. We allow for more time so the guider has
time to prepare either side.
=> Hardcode appointment duration to 45 minutes

app/models/appointment.rb
This is defined for free with Rails enums. You also get the
bang-equivalent for transitioning to that particular state. FYI.
=> Don't redefine `#no_show?`

app/lib/appointment_importer.rb, app/models/appointment.rb, spec/features/pension_wise_imports_historical_data_spec.rb, spec/models/appointment_spec.rb
Marks freshly imported records with a more obviously fake date of birth.
This is to ensure guiders don't inadvertently read back the date of birth
to their customer.
=> Mark imported records with an obviously fake DOB

app/controllers/mail_gun/drops_controller.rb, app/forms/drop_form.rb, spec/forms/drop_form_spec.rb
This stops staging hooks firing and clobbering production records.
Having hooks running in the staging isn't important as drops are not
actioned in this environment. This matches the planner behaviour for
processing drop hooks.
=> Ensure hooks only respond to production requests

app/assets/javascripts/modules/calendar.es6
- Altered where calendar loading view gets inserted, to ensure
that loading graphic is shown when calendar is first rendered
=> Ensure that ajax loading graphic shows when calendars first load

app/assets/javascripts/modules/calendar.es6, app/assets/javascripts/modules/calendars/appointment-availability.es6, app/assets/javascripts/modules/calendars/company.es6, app/assets/javascripts/modules/calendars/guider-slot-picker.es6, app/assets/javascripts/modules/calendars/my-appointments.es6, app/assets/stylesheets/components/_calendars.scss, app/assets/stylesheets/lib/_colours.scss
- Appointments in the past get a lighter background colour
- this includes cancelled appointments which have got a
slightly different red colour which has the same
saturation as a non-cancelled appointment
- the lighter colour helps the user get a visual sense
of what appointments have now happened
=> Style appointments in the past in a lighter colour

app/models/assignment_activity.rb, app/views/activities/_assignment_activity.html.erb, spec/features/guider_views_their_activities_spec.rb, spec/models/assignment_activity_spec.rb
The way these messages were worded prior to this change implied the
assignment was a user-driven activity. This is incorrect since
allocation is randomised and assigned via the system.
In the case of reassignment we now display richer text describing which
resource manager made the selection and which guider was selected.
=> Refine allocation / assignment messages

app/assets/javascripts/modules/holiday-types.es6, app/assets/stylesheets/components/_holiday.scss, app/controllers/holidays_controller.rb, app/forms/batch_upsert_holidays.rb, app/views/holidays/_form.html.erb, spec/forms/batch_upsert_holidays_spec.rb, spec/support/sections/single_day.rb
=> Don't allow holidays with backwards date ranges

app/assets/javascripts/modules/calendars/company.es6, app/assets/javascripts/modules/calendars/my-appointments.es6, app/controllers/appointments_controller.rb, db/migrate/20161208205325_add_start_at_index_on_appointments.rb, db/schema.rb
Let the browser cache the responses based on the given etags. These
responses are trivially cacheable and testing locally shows that paging
back and forth through days that trigger conditional 304s drops the
response times for this endpoint down to ~100ms from ~500ms.
The recent `#stale?` addition performs checks to determine the freshness
of the given model / model collection instance by counting the elements
and retrieving the `MAX("appointments"."updated_at")`, merging the
same `where` clauses for the given model / model collection.
Since we had no index on this column this query was very slow (at least
in postgresql terms) in the order of `~100ms`. Adding this index drops
this down to `~1ms` which is quite some gain.
=> Speed up appointments JSON responses

app/assets/javascripts/modules/calendars/company.es6, app/assets/javascripts/modules/calendars/my-appointments.es6, app/controllers/bookable_slots_controller.rb, db/migrate/20161209113503_add_timestamps_to_bookable_slots.rb, db/migrate/20161209134519_add_index_on_bookable_slots.rb, db/migrate/20161209134951_add_index_to_holidays.rb, db/schema.rb, spec/support/sections/calendar.rb
Use conditional GETs for bookable slot responses. In order to generate the
cache digests, Rails needs timestamps on the models so I added those.
The changes surfaced a timing issue on guiders / resources so I also
addressed this issue.
Adding indexes on the start and end dates for both holidays and
bookable slots lends quite an improvement in querying response times across
the board since most queries require these clauses in unison.
=> Cache bookable slots responses

spec/features/resource_manager_manages_holidays_spec.rb
This was failing intermittently due to what I suspect was a timing issue
around the presence of calendar events which are loaded asynchronously.
=> Attempt to fix the spec timing issue with holiday

app/jobs/generate_bookable_slots_for_user_job.rb, spec/jobs/generate_bookable_slots_for_user_job_spec.rb
This was using variadic arguments needlessly since at each callsite we
pass a singular instance of a guider.
=> Pass singular arguments to this job

.rspec_parallel, Gemfile, Gemfile.lock, config/database.yml
Run specs in parallel across your multiple cores / processes. On my
machine this drops the spec runs to around 35 seconds.
You can still run `rake` as normal or `rspec` if you want to run specs
serially so this is opt-in for now. To get this setup on your machine
first pull this branch, then:
$ bundle exec rake parallel:create
This creates multiple databases to run against.
$ bundle exec rake parallel:prepare
This ensures each database is at the same version, migration-wise. You
should run this after running migrations as normal too.
Run the specs:
$ bundle exec parallel_rspec
You can choose how many processes to run against by exporting
`PARALLEL_TEST_PROCESSORS=X` where `X` is the number of processes. A
good rule of thumb is to use the same number as physical cores.
I've not set this up …
=> Parallelise specs across multiple processes

app/assets/javascripts/modules/calendar-events.es6, app/assets/javascripts/modules/calendars/company.es6, app/assets/javascripts/modules/calendars/my-appointments.es6, app/views/allocations/show.html.erb, app/views/company_calendars/show.html.erb, app/views/layouts/application.html.erb, app/views/my_appointments/show.html.erb, spec/features/guider_views_appointments_spec.rb, spec/support/sections/calendar.rb
TPAs have requested that guiders can see appointment change notifications from any page, not just the My Appointments page. This change fixes that, and also ensures that the relevant calendars are updated in the process.
Also, fix [HTML injection vulnerabilities](https://en.wikipedia.org/wiki/Code_injection#HTML_script_injection) in the qtip rendering and notification modal.
=> Notify guiders from anywhere when appointments change

app/controllers/application_controller.rb, config/environments/production.rb, config/initializers/filter_parameter_logging.rb
Provides the necessary configuration to log params while honouring the
Rails `filter_parameters` configuration to strip sensitive information
from the logs.
=> Log params while filtering sensitive information

app/models/holiday.rb, app/serializers/holiday_serializer.rb, spec/factories/holidays.rb, spec/features/resource_manager_manages_holidays_spec.rb, spec/models/holiday_spec.rb
FullCalendar shows all day events exclusive of the end date, so
that means if we have a two day holiday, it will always show up as one
day in the all day slot.
To get around this we add one day to all holidays that are "all day".
Also see: http://stackoverflow.com/questions/27604359/fullcalendar-event-spanning-all-day-are-one-day-too-short
=> Fix bug where all day holidays were showing up as 1 day less in length

app/assets/javascripts/modules/calendar.es6
- When ajax responses for appointments get returned really quickly
we were seeing a quick flash of the ajax loader graphic
- there doesn't seem any point in showing the ajax loader unless
the user is really seeing a slow response in getting data back
- now shows the ajax loader after 0.2 of a second
=> Delay showing of ajax loader

app/assets/stylesheets/components/_appointment_search.scss, app/views/appointments/search.html.erb
- added caption for screen readers
- improved alignment of text in cells, to middle align with buttons
=> Improvements to appointment search results table

app/assets/stylesheets/components/_create_appointment.scss, app/views/appointments/new.html.erb, app/views/appointments/preview.html.erb, spec/features/agent_manages_appointments_spec.rb
- Combined certain fields so that it reads better when
an agent is reading back details to a customer
- Make page shorter
- Improve copy (Preview -> Review)
=> Improve layout of review of new appointment

app/assets/stylesheets/components/_guiders.scss, app/views/users/index.html.erb
- when guider is inactive, add screen reader text
- vertical align center rows, to aid readability
=> Improve Accessibility and look of guiders list

app/models/bookable_slot.rb, spec/models/bookable_slot_spec.rb
For example if a slot ends at 10:30 and a holiday starts at 10:30, we
now allow that slot to be booked. Also if a slot starts at 11:30 and a
holidays ends at 11:30 we also allow that slot to be booked. Previously
none of these would work.
=> Allow slots that start directly after or end directly before holidays

app/models/appointment.rb, spec/models/appointment_spec.rb
This ensures customer names are cased correctly as the agents tend to
use a mixture of case when inputting names.
=> Format first and last name for customer

app/models/bookable_slot.rb, spec/models/bookable_slot_spec.rb
In production we were having issues when holidays start at the exact same time as bookable slots, or end at the exact same time. We expected the slots to be hidden, but they were not.
=> Hide bookable slots when holiday starts/ends at same time as the slot

app/models/appointment_search.rb
The guiders association was being loaded after the fact, and causing an
N+1 query. This also occurred when querying with the `joins`
declaration, thus the need for `joins` and `includes`.
=> Removes the N+1 querying when searching

Gemfile, Gemfile.lock, app/jobs/pusher_activity_notification_job.rb
This is a weird one. The activities should be committed synchronously
before the jobs are scheduled but somehow this isn't occurring.
This is a temporary fix to ensure they're at least being run. The jobs
are retried up to a maximum of 5 times, with a 1 second delay between
each. This should recover the `ActiveJob::DeserializationError`
failures (in most cases I'd expect it to be successful upon the first
retry).
=> Retry jobs until activity is committed

Gemfile, Gemfile.lock, app/jobs/pusher_activity_notification_job.rb
Reverts guidance-guarantee-programme/telephone_appointment_planner#408
These were still borked. Somehow the arguments weren't getting passed upon rescheduling.
=> Revert "Retry jobs until activity is committed"

app/forms/appointment_report.rb, spec/features/resource_manager_downloads_appointment_reports_spec.rb
The appointment report was only including appointments that were before the beginning of the day of
the last day in the range.
=> Appointment report shows appointments until the end of day in range

app/presenters/appointment_search_result_presenter.rb, app/views/appointments/search.html.erb
Remove old code that was used when we handled search result highlighting
in the backend
=> Fix HTML injection vulnerability on Appointments#search

app/models/bookable_slot.rb, spec/models/bookable_slot_spec.rb
When a slot had both a cancelled and a pending appointment assigned to
them, then the slot still showed as available.
=> Fix bug where slots with cancelled+pending appointments weren't excluded

config/environments/production.rb
Adding these ensure public caches work properly for our assets.
=> Add missing cache control headers for assets

spec/rails_helper.rb
Sometimes my tests were slow waiting for this external asset to be served.
It has no bearing on the specs so we can blacklist it.
=> Blacklist pusher's external JS request in test

Gemfile, Gemfile.lock
Using homebrew's bottled binaries is so much faster on my local machine
when running the specs. I can only assume the `phantomjs-binaries` bundled
binary is built with weird or no optimisation flags.
This change alone yields at least a 20 second improvement on spec timings
for me and shouldn't impact anyone else. Just ensure you've the latest
phantomjs binary on your `PATH`.
Sometimes my tests were slow waiting for pusher's external asset to be served.
It has no bearing on the specs so we can blacklist it.
=> Don't use gem bundled phantomjs binaries

app/views/appointments/search.html.erb, spec/features/agent_searches_for_appointments_spec.rb, spec/support/pages/search.rb
- Improves readability of customer name
- Moved created date to after appointment date, so dates
are together
=> Combine customer first/last name on search results

Gemfile, app/controllers/activities_controller.rb, app/jobs/pusher_activity_notification_job.rb, app/models/assignment_activity.rb, app/models/audit_activity.rb, app/models/create_activity.rb, app/models/drop_activity.rb, spec/models/assignment_activity_spec.rb, spec/models/audit_activity_spec.rb, spec/models/create_activity_spec.rb, spec/models/drop_activity_spec.rb
Rails enlists an emplicit transaction around `save` or `update`
operations and callbacks fire within this enlisted transaction. We hook
into the audited gem's `after_audit` callback to enqueue pusher
notification jobs but this causes a race condition that in circa 20% of
the time results in the job relying on this data being dequeued before
the database transaction has committed said data.
Thanks to the unique way in which Active Job deserializes model-based
arguments to the jobs, an `ActiveJob::DeserializationError` is raised
that is not retried in the traditional sense.
Changing the job arguments to their ID references means we sidestep this
behaviour so when dependent pieces of data cannot be retrieved using
`Model.find` an `ActiveRecord::RecordNotFound` error is raised and our
retry …
=> Don't rely on GlobalID for these job arguments

app/assets/javascripts/modules/activity-feed.es6, app/assets/stylesheets/components/_activity.scss, app/assets/stylesheets/helper/_show_hide.scss, app/jobs/pusher_activity_notification_job.rb, app/views/activities/_activity.html.erb, app/views/activities/_activity_feed.html.erb, app/views/activities/_assignment_activity.html.erb, app/views/activities/_audit_activity.html.erb, app/views/activities/_create_activity.html.erb, app/views/activities/_drop_activity.html.erb, app/views/activities/_message_activity.html.erb, app/views/activities/_reminder_activity.html.erb, app/views/activities/index.html.erb, spec/features/user_views_booking_activities_spec.rb, spec/support/pages/edit_appointment.rb
- Show all the activities when JS is disabled
- Show up to three activities on page load
- One list instead of two for displaying activities
- aria-live="polite" on activities list so changes
get read out to screen reader users
=> Improve accessibility and display of activity feed

app/models/appointment.rb, spec/models/appointment_spec.rb
The likelihood of this is pretty low but sticking with 1900-01-01 as a
cut-off for valid date of birth values will resolve the issues that
TPAS have raised.
=> Ensure date of birth is at least 1900

spec/rails_helper.rb, spec/support/poltergeist.rb
This yields a good improvement as the specs aren't unnecessarily
waiting around for pusher's analytics assets. It does however highlight
even more timing issues in our specs that were being masked by the long
wait times for these assets.
=> Correct pusher asset blacklisting during specs

spec/features/guider_views_appointments_spec.rb
We need to wait for the appointments to appear before we can interact
with them in the specs. This ensures that happens explicitly.
=> Wait for appointments explicitly

app/models/appointment.rb, spec/models/appointment_spec.rb
We default a missing email to an empty string, so our reminder guard
should check for the same criterion.
=> Correct email presence check

spec/features/agent_searches_for_appointments_spec.rb
1) Agent searches for appointments searches for a name with multiple results
Failure/Error: expect(actual).to eq expected
expected: ["Joe Bruen", "Joe O'kon"]
got: ["Joe O'kon", "Joe Bruen"]
=> Fix flaky search spec

app/models/bookable_slot.rb, spec/models/bookable_slot_spec.rb
If an appointment start_at or end_at is BETWEEN the bookable slot
start_at and end_at, then hide the bookable slot.
@benbarnett @benlovell thoughts?
=> Hide bookable slots that are partially overlapped by appointments

.rubocop.yml, app/controllers/api/v1/bookable_slots_controller.rb, app/models/bookable_slot.rb, app/models/user.rb, config/routes.rb, spec/factories/users.rb, spec/requests/bookable_slots_api_spec.rb, spec/support/user_helpers.rb
This adds a new JSON API endpoint at `/api/v1/bookable_slots` and
returns a payload like:
```
[
"2017-01-01": [ "12:00", "13:00", "15:00" ],
"2017-01-02": [ "12:10", "14:10" ]
]
```
It requires the `pension_wise_api` permission to be present for the
requesting user.
This first cut relies on grouping, de-duping and sorting in memory which
isn't ideal. The alternative turned into the beastiest SQL query I've
ever written and wasn't ideal for maintenance purposes, though a great
deal more performant.
Running this across the booking window (6 weeks) on a copy of the
production database, but in development mode yields the full response
in ~700ms.
=> Add bookable slots API for customer booking

app/controllers/api/v1/bookable_slots_controller.rb, app/models/user.rb, spec/factories/users.rb, spec/requests/bookable_slots_api_spec.rb, spec/support/user_helpers.rb
This is public information once it gets bound to the slot picker so
there is really no need to require authentication.
=> Permit unauthenticated access to this API

app/models/bookable_slot.rb, spec/requests/bookable_slots_api_spec.rb
Ordering was busted since we weren't explicitly ordering before doing
the necessary transformations. We now order by the sliced up / grouped
start date for the bookable slot.
=> Don't rely on natural ordering

app/models/bookable_slot.rb, spec/requests/bookable_slots_api_spec.rb
To avoid unnecessary parsing tricks on the client we now need to return
the full ISO timestamp for the individual bookable slots.
=> Use the full timestamp in the slots response

app/forms/appointment_report.rb
Since we corrected the data internally we only store these as
non-nullable booleans. Knowing this we can just cast to `text` instead
of the more complex `CASE`, reporting incorrectly.
=> Correct boolean output for opt-in flag

app/controllers/api/v1/appointments_controller.rb, app/forms/api/v1/appointment.rb, app/models/appointment.rb, app/models/user.rb, config/routes.rb, db/migrate/20170113163304_add_dc_pot_confirmed_to_appointments.rb, db/schema.rb, spec/factories/appointments.rb, spec/factories/users.rb, spec/models/appointment_spec.rb, spec/requests/appointments_api_spec.rb, spec/support/user_helpers.rb
This provides the basis for the bookings API at:
`POST /api/v1/appointments`
Callers will need the `pension_wise_api` permission from signon.
The form object is versioned using the same scheme as the API but since
the model and form classes are the same and Rails scoping is stupid,
I've had to dud alias the model class under a `Models` namespace so we
can qualify the scoping when calling the model `Appointment` from the
API `Appointment`.
=> Introduce bookings API

app/assets/javascripts/modules/calendars/guider-slot-picker.es6, app/models/slot.rb, app/views/schedules/_form.html.erb, db/migrate/20170116164058_remove_slots_that_fall_on_weekends.rb, spec/factories/schedules.rb, spec/features/resource_manager_manages_schedules_spec.rb, spec/models/slot_spec.rb, spec/support/pages/new_schedule.rb
- Delete slots that were created on Saturdays and Sundays.
- Stop adding weekend slots in JS
- Stop adding weekend slots in db:seed
http://momentjs.com/docs/#/get-set/day/
NOTE: Whoever merges this MUST run `rake jobs:bookable_slots:generate`.
=> Ensure no slots are generated on weekends

app/controllers/api/v1/appointments_controller.rb, app/forms/api/v1/appointment.rb, spec/requests/appointments_api_spec.rb
Permit clients to send a customer's marketing preferences as part of the
API payload. This is then persisted in the appointment record.
=> Accept opt-out preference in appointments API

app/controllers/api/v1/appointments_controller.rb
We pass params to the API without wrapping them, so rails normally will
wrap the JSON in { "appointments" : JSON }. Disable this, so that
the data we receive looks like the data we send.
=> Don't wrap appointment parameters in appointments api

app/models/appointment.rb, spec/models/appointment_spec.rb
'presence: true' validations don't work for booleans because:
`false.present? => false`
=> Validate that dc_pot_confirmed is not nil correctly

app/forms/api/v1/appointment.rb, app/models/appointment.rb, app/models/bookable_slot.rb
Don't search for `end_at` too, because it doesn't really matter if we do
or don't. This also means we can search for a slot if we only know the
`start_at`, like in the case of the `appointments` `create` API.
=> Only search for guider slots with start_at

app/views/appointment_mailer/confirmation.html.erb, app/views/appointment_mailer/confirmation.text.erb
Prior to this change the date / time formatting was incorrect in the
confirmation email. As per other transactional emails - we split the
date and time to be displayed separately but this wasn't happening here.
Also - in the text part - we should indent the date header and value
since the whitespace here is meaningful and will be preserved by textual
clients.
=> Use consistent dates in mailer templates

app/constraints/authenticated_user.rb, config/routes.rb, spec/requests/sidekiq_authentication_spec.rb, spec/support/user_helpers.rb
It turns out there were multiple problems with how this was
implemented. This ensures only authenticated users are permitted access
to the sidekiq control panel.
=> Correctly authenticate for sidekiq panel

app/models/bookable_slot.rb
Given the size and cartesian products of the various join filters required
to infer and limit the bookable slots, we were reducing down from multiple
millions of rows. Limiting the scope and range of the join filters speeds
this up from multiple seconds (across our working set) to just a few
milliseconds.
We can also rely on the database to order the slot times which also yields a
reasonable reduction in runtime.
I'll create further PRs reducing the ranges used on bookable slots elsewhere.
=> Reduce runtime for the slots API

app/controllers/api/v1/appointments_controller.rb, spec/requests/appointments_api_spec.rb
Responds with the path to our freshly minted appointment so we can
reference this in API clients.
=> Return the `Location` header upon creation

app/controllers/api/v1/application_controller.rb, app/controllers/api/v1/appointments_controller.rb, app/controllers/api/v1/summary_documents_controller.rb, app/jobs/pusher_activity_notification_job.rb, app/lib/summary_document_link.rb, app/models/appointment.rb, app/models/summary_document_activity.rb, app/views/activities/_summary_document_activity.html.erb, app/views/appointments/edit.html.erb, config/initializers/summary_document_url.rb, config/routes.rb, spec/models/appointment_spec.rb, spec/requests/summary_documents_api_spec.rb
* Allow guiders to open the summary document generator with data prepopulated
* add an endpoint so the summary document can trigger an activity entry once it has been created.
Need to set env variable:
```ruby
SUMMARY_DOCUMENT_GENERATOR
```
=> Add a link to pre-populate the summary document

app/lib/summary_document_link.rb
Previously this was taking their full name from TAP (SignOn)'s
database. As their name is stored in a single field, we need to
split that string and take the first word of it.
=> Send only the guider's first name across to the summary document

app/assets/stylesheets/components/_activity-feed.scss, app/assets/stylesheets/components/_activity.scss, app/assets/stylesheets/components/_appointment_search.scss, app/assets/stylesheets/components/_booking-details.scss, app/assets/stylesheets/components/_dob-form-field.scss, app/assets/stylesheets/helper/_govuk_admin_template_overrides.scss, app/views/activities/_activity_feed.html.erb, app/views/appointments/edit.html.erb, app/views/appointments/search.html.erb
**Top of edit screen**
**Booking details**
**Appointment search**
=> Making the appointment edit and appointment search pages mobile friendly

app/assets/javascripts/modules/calendar.es6, app/assets/stylesheets/components/_calendars.scss, app/assets/stylesheets/helper/_bootstrap_overrides.scss
**Improved spacing around buttons**
**Increased touch area for checkbox**
- Improved spacing between calendar buttons
- Increased touch area of checkbox
- Ensure that jump to date calendar popup appears
correctly in all viewport widths
=> Improve mobile friendliness of book appointment page

app/assets/javascripts/modules/calendars/allocations.es6, app/assets/stylesheets/components/_calendars.scss
Users were sometimes mistakenly changing the start time of
an appointment, because it was difficult to see what time
exactly they were dragging an appointment to.
This provides them the start time of where the item has
currently been dragged to, making it easier to spot
potential mistakes.
=> Show the event start time as you drag an appointment

app/controllers/application_controller.rb, app/controllers/appointments_controller.rb, app/models/appointment.rb, config/locales/en.yml, spec/features/agent_rebooks_appointments_spec.rb, spec/support/pages/edit_appointment.rb
We must ensure bookable slots are returned to the pool when an
appointment is rebooked.
=> Guard against rebooked pending appointments

Gemfile, Gemfile.lock, app/assets/javascripts/modules/advanced-select.es6, app/assets/stylesheets/helper/_vertical-align.scss, app/controllers/groups_controller.rb, app/forms/create_group_assignments.rb, app/views/groups/index.html.erb, spec/features/resource_manager_manages_guiders_spec.rb, spec/forms/create_group_assignments_spec.rb, spec/support/pages/manage_groups.rb
Previously users have had to remember the exact spelling of a group
in order to add users to existing one - sometimes creating
problems where a typo ends up creating a new tag
This uses the select2 tags feature to allow someone to select
an existing tag or tags, or create a new one
=> Allow users to add groups from an existing list or create a new one

app/controllers/api/v1/application_controller.rb
We were doing this for regular controllers but not for our API-based
controllers. This will help us debug issues that occur in staging and
production.
=> Log filtered API parameters with lograge

app/controllers/api/v1/dropped_summary_documents_controller.rb, app/models/dropped_summary_document_activity.rb, app/views/activities/_dropped_summary_document_activity.html.erb, config/routes.rb, spec/requests/summary_document_dropped_api_spec.rb
Exposes an API endpoint at
`/api/v1/appointments/:id/dropped_summary_documents` that creates an
activity - notifying the owning guider when an attempted (GOVUK notify)
delivery failed and thus prompting them to action.
=> Expose an API for notify-based delivery failures

app/controllers/api/v1/appointments_controller.rb, app/jobs/website_appointment_slack_pinger_job.rb
We should notify slack when a booking is received from the main Pension
Wise website, as part of the customer journey. This helps us keep track
of how many bookings are being made during the A/B test and gradual
rollout.
=> Notify slack on customer bookings

app/views/activities/index.html.erb, app/views/allocations/show.html.erb, app/views/appointment_reports/new.html.erb, app/views/appointments/edit.html.erb, app/views/appointments/new.html.erb, app/views/appointments/preview.html.erb, app/views/appointments/reschedule.html.erb, app/views/appointments/search.html.erb, app/views/company_calendars/show.html.erb, app/views/groups/index.html.erb, app/views/holidays/edit.html.erb, app/views/holidays/index.html.erb, app/views/holidays/new.html.erb, app/views/my_appointments/show.html.erb, app/views/schedules/edit.html.erb, app/views/schedules/new.html.erb, app/views/users/edit.html.erb, app/views/users/index.html.erb, app/views/users/sort.html.erb, app/views/utilisation_reports/new.html.erb, config/locales/en.yml
Each page should have it's own tailored title to
aid bookmarking pages, and helping users know
which page they are on in the tab of a browser
=> Add page titles across the app

app/views/appointments/search.html.erb, spec/features/agent_searches_for_appointments_spec.rb
Switch feature to js and use javascript to set the date
following warnings from Capybara about setting the value
of a read only field.
=> Make appointment search date range read only

app/lib/notifier.rb
We were occasionally sending update emails when the status changes
along with other notifiable attributes. By simply changing the
precedence to check for status updates first we will always send the
correct notifications when the status changes.
=> Change notification precedence

.travis.yml
This brings TAP inline with Pension Guidance where any
branch named prototypes/* will not run on travis
=> Exclude prototype branches from being run on Travis

app/presenters/appointment_search_result_presenter.rb, app/views/activities/_activity.html.erb, app/views/appointments/edit.html.erb, spec/features/guider_edits_an_appointment_spec.rb
This ensures timestamps are formatted with the correct offset for
'London'. Start and end timestamps for appointments, holidays, slots and
such are unaffected by this change as they're expressed in UTC without
an offset.
=> Display timestamps respective of DST

app/models/appointment.rb, app/models/bookable_slot.rb, spec/models/appointment_spec.rb
We were previously calculating the two business days grace period from
the current date and time. We should have calculated this from the close
of play and appointments have inadvertently been created.
=> Calculate grace period from close of play

app/lib/notifier.rb, spec/lib/notifier_spec.rb
While the actual email was a noop thanks to the absence of a customer email
address on the associated appointment we were incorrectly creating
activities. This change ensures activities are only created (and skips a
heap of other machinery) when a customer email address is present.
=> Ensure activities are only created when necessary

db/migrate/20170330173341_set_defaults_on_appointments.rb, db/schema.rb, spec/models/appointment_spec.rb
These fields are usually initialised to `nil` so when a form is bound
and submitted the values change to empty strings and are thus considered
'changed'. While technically true, the generated activity messages are
confusing since no noticeable change occurs to the user.
Initialising these fields to empty strings ensures that when the
comparison is made no changes are detected.
=> Default fields to avoid phantom audit messages

app/models/appointment.rb, spec/models/appointment_spec.rb
This is a temporary hack, please forgive me.
Appointments are stored / displayed in UTC but we're currently in BST.
An appointment scheduled for '12:20' actually takes place at '11:20'
according to the server, so when the appointment is updated after it
ends the `future?` check passes since '12:20' is greater than '11:20'.
If we substract an hour from the appointment's start time, we end up
with a true representation of time to compare with.
=> Allow for appointments being displayed in UTC

app/models/bookable_slot.rb, spec/models/bookable_slot_spec.rb
This will account for timezone discrepancies and is another ugly hack
(tm) however temporary, to workaround the timezone issues until we get
a proper workable solution in place.
Resource managers were seeing slots that have actually passed due to
the discrepancy between UTC and BST. This change ensures we add another
hour grace period to the first potentially available slot.
=> Bump default start date for calendars by an hour

app/assets/javascripts/modules/calendars/appointment-availability.es6
This ensures we parse the dates as UTC before comparison and thus
causes the originally selected slot to be highlighted after the form
roundtrips.
=> Reselect chosen slot after roundtripping

app/controllers/appointments_controller.rb, app/lib/summary_document_link.rb, app/models/appointment.rb, app/views/appointments/_personal_details_form.html.erb, app/views/appointments/preview.html.erb, db/migrate/20170330154903_add_type_of_appointment_to_appointments.rb, db/schema.rb, spec/features/agent_manages_appointments_spec.rb, spec/support/pages/new_appointment.rb
This gives agents and others the ability to specify the type of appointment
they expect the customer to have. This will be fed to the summary document
generator so TAP then becomes the canonical source for this piece of
information.
=> Allow management of appointment type

app/assets/javascripts/modules/customer-age.es6, app/assets/javascripts/modules/type-of-appointment.es6, app/models/appointment.rb, app/views/appointments/_personal_details_form.html.erb, db/migrate/20170405125850_default_appointment_type.rb, db/migrate/20170405141224_update_appointments_with_inferred_type.rb, db/schema.rb, spec/factories/appointments.rb, spec/features/agent_manages_appointments_spec.rb, spec/models/appointment_spec.rb
This change preselects the correct appointment type from the provided date
of birth when booking / modifying an appointment. It's possible the agent,
guider or resource manager will want to override this if they spot the
appointment is within a few months of a particular range - so this is also
possible.
=> Update appointment type from date of birth

app/controllers/activities_controller.rb, app/views/activities/index.html.erb
To avoid this page taking ages to load and improve
performance for users, this adds pagination to the
list of activities for a guider.
=> Adds pagination to activities index page

app/assets/javascripts/modules/calendar.es6
The `moment` or `now` is local time but the appointment end is UTC.
A comparison was made to highlight past appointments during the
course of the day.
This resolves the discrepancy (using an ugly hack) until we can put
proper timezone handling in place. We clone the end date so we don't
mutate the actual underlying time.
=> Fix timezone discrepancy for past appointments

app/models/activity.rb, spec/models/dropped_summary_document_activity_spec.rb
This ensures dropped summary document mailings are prioritised activities
so people can also ignore these and do nothing about them.
=> Dropped summary documents are high priorities

app/models/activity.rb, app/models/appointment.rb, app/models/drop_activity.rb, app/models/dropped_summary_document_activity.rb, app/views/shared/_navigation.html.erb, spec/features/notifications_spec.rb, spec/support/pages/base.rb
In the case of dropped summary documents these are always the guider's
responsibility to action, so only they will receive the high-priority
notifications.
In the case of other dropped emails - for now we will notify both the
guider and the agent - so long as the agent is not the Pension Wise website
API agent. This is despite the `owner` of the activity always being the
guider.
Since these two activities are always considered 'high priority' we can do
away with the guard and move the event hooks into the concrete activity
classes.
=> Ensure notifications are directed accurately

app/controllers/mail_gun/drops_controller.rb, app/forms/drop_form.rb, app/models/drop_activity.rb, spec/features/notifications_spec.rb, spec/forms/drop_form_spec.rb, spec/models/drop_activity_spec.rb, spec/requests/mailgun_drop_notification_spec.rb
We now notify and assign responsibility for dropped / bounced emails to the
agent making the booking. For any other dropped emails we assign the
responsibility and notify the guider.
Mailgun returns the original headers we supply when sending the emails so
we pick the `message_type` reliably from the inbound webhook.
=> Notify individuals based on the type of message

config/initializers/working_hours.rb, spec/models/bookable_slot_spec.rb
We were not previously counting bank holidays or other public holidays
when advancing by 'working days' so was a chance customers could
actually book within the lock down period prior to this change.
=> Count public holidays if calculating working days

spec/models/bookable_slot_spec.rb
Test was failing due to it assuming it was not being run after a bank holiday weekend, so use `travel_to` to remove this possibility.
=> Address brittle bookable slot spec

app/models/appointment.rb, spec/factories/activities.rb, spec/features/appointment_reminder_spec.rb, spec/models/appointment_spec.rb
This should now:
- observe a 48 hour window ahead of appointments for sending reminders
- not resend reminders when called multiple times during that window
- once 48 hours from the first reminder passes (i.e. approximately original time of the appointment when first reminded), will start sending reminders again should we re-encounter the 48 hour window ahead of an appointment (i.e. if it's been rescheduled into the future)
=> Rework `Appointment.needing_reminder`

.travis.yml, Gemfile, Gemfile.lock, spec/support/poltergeist.rb
For some reason (probably `exec`ing a new process every time, but I
didn't check) the binaries and process overhead from
`phantomjs-binaries` adds around an extra 30 seconds to an `rspec` run
on my machine. We switched away from `phantomjs` in the past since it
used an unreliable bitbucket CDN that was often rate-limited in Travis,
it seems this has been addressed now so switching back to this gem
yields a ~30 second reduction in spec runs.
=> Switch to `phantomjs` gem for binaries

app/assets/javascripts/modules/calendars/appointment-availability.es6, app/assets/stylesheets/components/_appointment-availability-calendar.scss
A lack of 'href' attributes on the event links in the calendar
meant that they could not be tabbed to.
This forces an href and also adds additional information for
screen reader users to understand what is currently selected
and what the number in an event actually means (guider count)
=> Allowing appointment slots to be tabbed to on availablity calendar

app/models/appointment.rb, spec/models/appointment_spec.rb
This ensures the appointment type is correctly inferred from the customers age
at the time of their appointment.
=> Calculate type from age at appointment

Gemfile, Gemfile.lock, config/initializers/oj.rb
As per planner, we'll definitely see some benefit from faster
serialization for our JSON APIs.
=> Use OJ for faster JSON serialization

Gemfile, Gemfile.lock
Hopefully for obvious reasons.
=> Use SSL for `github` references

app/models/appointment.rb, app/views/appointment_mailer/cancelled.html.erb, app/views/appointment_mailer/cancelled.text.erb, app/views/appointment_mailer/missed.html.erb, app/views/appointment_mailer/missed.text.erb, app/views/shared/email/_appointment_details.html.erb, app/views/shared/email/_appointment_details.text.erb, spec/models/appointment_spec.rb
=> Display time zone information in customer emails

app/jobs/customer_update_job.rb, app/lib/notifier.rb, db/migrate/20170620093338_delete_incorrect_email_activities.rb, db/schema.rb, spec/jobs/customer_update_job_spec.rb, spec/lib/notifier_spec.rb
We need to thoroughly guard against notification activities for appointments
without customer-supplied email addresses. There have been ~500 created for
appointments and this bug was reported by TPAS.
Review commit-by-commit.
=> Thoroughly guard against appointment activities

app/assets/javascripts/modules/calendars/company.es6, db/seeds.rb
So, the solution turned out to be as simple as what I could swear I tried right at the start.
Possibly one red herring was that the test data used ActiveSupport's `end_of_day` time helper which set the end of the seeded holidays to 23:59:59 whereas holidays created within tap are 10:00 - 11:00, etc, which threw my initial assessment of the situation.
I've included a change to the seeds to address this.
Some screencaps of the behaviour below.
=> Prevent hiding of bookable slots that are adjacent to holidays

app/models/appointment.rb, spec/models/appointment_spec.rb
We were previously locked to 30 working days, though the booking window
elsewhere was increased to 8 weeks.
=> Allow appointments up to 40 days in advance

app/assets/javascripts/modules/guider-schedules-chart.es6
This was changed to 8 weeks but this part was missed.
=> Corrects the visible schedule window

app/controllers/api/v1/appointments_controller.rb, app/controllers/appointments_controller.rb, app/forms/api/v1/appointment.rb, app/lib/where_you_heard.rb, app/models/appointment.rb, app/views/appointments/_personal_details_form.html.erb, app/views/appointments/preview.html.erb, db/migrate/20171021082029_add_where_you_heard_to_appointments.rb, db/schema.rb, spec/factories/appointments.rb, spec/features/agent_manages_appointments_spec.rb, spec/requests/appointments_api_spec.rb, spec/support/pages/new_appointment.rb
Allows clients to create appointments and assign the customer's
choice for where they first heard of Pension Wise.
=> Allow `where_you_heard` to be specified

app/models/appointment.rb, spec/models/appointment_spec.rb
Some bookings prior to the WDYH change will be unspecified so when
these are the basis of a rebooking we ought not to validate for WDYH
presence.
=> Don't validate presence of WDYH when rebooked

Gemfile, Gemfile.lock
This allows us to drop the pre-release dependency for `rails-observers`.
=> Bump `audited`

Gemfile, Gemfile.lock, app/jobs/sms_appointment_reminder_job.rb, app/lib/sms_appointment_reminders.rb, app/models/appointment.rb, app/models/sms_reminder_activity.rb, app/views/activities/_sms_reminder_activity.html.erb, app/views/appointments/_personal_details_form.html.erb, spec/features/sms_appointment_reminder_spec.rb, spec/jobs/sms_appointment_reminder_job_spec.rb, spec/models/appointment_spec.rb
Sends SMS reminders via Notify, 48 hours before an appointment is due.
This needs to be scheduled.
=> Send SMS reminders 48hr before appointments

app/assets/stylesheets/components/_calendars.scss
These weren't clear enough prior to this change. I've darkened the
background slightly to aid contrast, and added a margin in the blocked
slot to help see the background through cancellations.
=> Better highlight blocked slots under cancellation

app/controllers/bookable_slots_controller.rb, app/models/appointment.rb, app/models/bookable_slot.rb, spec/models/appointment_spec.rb
This has passed so is no longer required.
=> Remove now redundant guider conference days

app/assets/javascripts/modules/calendars/allocations.es6
This was not enabled for this particular calendar but TPAS have
requested we change this behaviour.
=> Persist last date via calendar cookie

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/modules/date-time-picker.es6, app/assets/javascripts/modules/guider-select.es6, app/assets/stylesheets/application.scss, app/controllers/appointments_controller.rb, app/forms/api/v1/appointment.rb, app/helpers/user_helper.rb, app/models/appointment.rb, app/views/appointments/_schedule_form.html.erb, app/views/appointments/new.html.erb, app/views/appointments/preview.html.erb, app/views/appointments/reschedule.html.erb, db/seeds.rb, spec/features/agent_manages_appointments_spec.rb, spec/features/resource_manager_reschedules_an_appointment_spec.rb, spec/models/appointment_spec.rb, spec/support/pages/new_appointment.rb, spec/support/pages/reschedule_appointment.rb
Grants resource managers the ability to reschedule appointments on an
adhoc basis, ie not from the calendar schedule. When rescheduling the
resource manager is presented with a further option to select from
adhoc availability. When they select this they are then presented with
a date and guider to choose from.
=> Allow resource managers to adhoc reschedule

app/jobs/sms_appointment_reminder_job.rb
The only failures we see are related to invalid numbers being provided
by our service. There is no need for these to be retried yet should be
captured for operational metrics.
=> Swallow and publish notify client errors

app/models/appointment.rb, spec/models/appointment_spec.rb
Now appointments can be created at very short notice we need to guard
against this particular circumstance. By extending the window a few
hours we allow a grace period before sending a reminder.
=> Do not send reminders for fresh appointments

spec/features/user_views_booking_activities_spec.rb
This was causing intermittent timing issues during spec runs in the CI
environment.
=> Explicitly wait for the field to be cleared

app/models/appointment.rb, app/views/appointments/_availability_calendar.html.erb, app/views/appointments/_unable_to_assign.html.erb
These were not being shown when present and this causes confusion to
the agents when attempting to place appointments.
=> Ensure validation errors on `start_at` display

app/models/activity.rb, app/models/drop_activity.rb, spec/models/drop_activity_spec.rb
This ensures guiders are not alerted or assigned high-priority
activities when an email is permanently failed by mailgun. They will
continue to receive notifications and assignments for dropped summary
documents.
=> Do not alert guiders on drop notifications

config/initializers/working_hours.rb, spec/models/bookable_slot_spec.rb
This ensures the next working day logic is calculated correctly when
booking appointments or displaying availability.
=> Configure 2018 bank holidays

app/models/appointment.rb, app/models/bookable_slot.rb, spec/models/appointment_spec.rb, spec/models/bookable_slot_spec.rb
Cuts the initial grace period for bookings down to one business day, as
requested by TPAS.
=> Reduce grace period to one business day

app/models/appointment.rb, spec/factories/appointments.rb
When an email AND postal address is supplied, we should not be exporting
these appointments for print confirmation.
=> Ensure appointments with email are not printed

app/models/appointment.rb, spec/models/appointment_spec.rb
Don't permit both an email address and a postal address for
confirmation as they should be mutually exclusive.
=> Validate only an email/address is present

app/models/appointment.rb, spec/models/appointment_spec.rb
These errors were previously attributed to `base` and weren't being
displayed sensibly. Tagging them to the `email` field ensures they
appear in the correct context when creating an appointment.
=> Tag the `email` field with the errors

app/lib/scheduled_reporting_summary.rb, app/models/reporting_summary.rb, db/migrate/20180423115902_create_reporting_summaries.rb, db/schema.rb, spec/features/scheduled_reporting_summary_spec.rb
This will be scheduled to run every morning before the day's
appointments are due to start. It summarises availability over the
following four week period, inside of the regular booking window.
At the moment this is only concerned with TPAS guider appointments but
once we support multiple providers it will address other provider's
appointments also.
=> Summarise availability data for reporting

app/models/appointment.rb, app/models/status_transition.rb, db/migrate/20180425083620_create_status_transitions.rb, db/schema.rb, lib/tasks/statuses.rake, spec/models/appointment_spec.rb
Stores the status transition in an association when it is initially created
or upon a status change.
=> Store status transitions upon creation or changes

app/models/appointment.rb, app/models/sms_cancellation_activity.rb, spec/models/appointment_spec.rb, spec/models/sms_cancellation_activity_spec.rb
Unless the `pusher_notify_user_ids` are present, the feed is not updated
since they're tied to the update job.
=> Ensure the activity feed is updated in realtime

app/models/appointment.rb, app/models/bookable_slot.rb
Since the introduction of SMS cancellations we should include the newly
introduced `cancelled_by_customer_sms` status when querying by the
previous cancellation statuses to ensure reports are accurate.
=> Include SMS cancellations with regular ones

app/forms/sms_cancellation.rb, spec/forms/sms_cancellation_spec.rb
The reminder SMS tells the customer to reply 'Cancel' to cancel their
appointment so some customers respond literally. This change makes the
trigger text more permissive in regards to accepting optional quote
marks.
=> Be more permissive with SMS cancellation trigger

app/models/appointment.rb, spec/models/appointment_spec.rb
Increase the window for sms reminders to be both 7 days before and 2 days before.
https://trello.com/c/uLUWENbE
=> appointments need sms reminders at both 7 days and 2 days

app/lib/scheduled_reporting_summary.rb, app/models/bookable_slot.rb, spec/factories/bookable_slots.rb, spec/features/scheduled_reporting_summary_spec.rb
The currently released summary is generated based on TPAS availability only
for the timebeing. This change ensures availability is correctly
summarised, per organisation.
=> Summarise availability per provider

app/models/appointment.rb, spec/factories/appointments.rb, spec/jobs/sms_appointment_reminder_job_spec.rb, spec/models/appointment_spec.rb
We are sending reminders immediately after confirmations are sent in
the case of appointments booked that immediately fall within the 2 or 7
day reminder period for SMS and email reminders. This change ensures we
do not send these reminders unnecessarily.
=> Do not send reminders on same day as booked

app/models/user.rb
This has been shuffled around in signon to match Drumpchapel's previous
content ID, this is to allow booking managers from CAS/Drumchapel to
use both the planner and TAP in unison.
=> Switch CAS organisation ID

app/lib/summary_document_link.rb, spec/lib/summary_document_link_spec.rb
Now we support summaries from users with both face-to-face and telephone
permissions we need to pass this flag to distinguish.
=> Include telephone appointment identifier

app/controllers/appointments_controller.rb, app/models/appointment.rb, app/models/bookable_slot.rb, spec/models/appointment_spec.rb
Prior to this change there were instances of guiders being allocated
across the organisation boundaries when they had identically available
slots. This change ensures only TP agents can allocate across the
organisation boundaries. All other permeations of role/organisation are
restricted to their own guiders.
=> Add some determinism to guider selection

app/jobs/sms_appointment_reminder_job.rb, spec/jobs/sms_appointment_reminder_job_spec.rb
We do this elsewhere and it's important to include for telephone
customers as they can be situated anywhere in the world.
=> Include timezone with SMS reminder

app/presenters/audit_presenter.rb, app/views/changes/index.html.erb, spec/models/appointment_spec.rb
There are some edge-cases where the auditing 'owner' will be missing. In
these instances we can assume the change was made by 'The system' and
display this accordingly.
=> Display missing owner as 'The system'

app/models/appointment.rb, app/models/user.rb, spec/factories/appointments.rb, spec/features/guider_views_appointments_spec.rb, spec/features/notifications_spec.rb, spec/features/resource_manager_modifies_appointments_spec.rb, spec/models/appointment_spec.rb
Allows TPAS resource managers to reschedule appointments during guider
conference days that would otherwise be blocked out.
I had to also fix a bunch of stupid time-sensitive specs.
=> Allow TPAS managers to reschedule during conf

app/controllers/appointments_controller.rb
When rescheduling the appointment we mark the agent as the current
user, this is to ensure the permissions checks are carried out again.
This allows resource managers to assign appointments during the guider
conference days.
=> Set agent when rescheduling

app/models/appointment.rb, app/models/bookable_slot.rb, spec/models/bookable_slot_spec.rb
This has been causing TPAS many scheduling issues so we're reverting
back to a day while we review a course of action suitable to all
partners.
=> Revert grace period to two business days

app/views/appointments/new.html.erb
Moves the date picker under the customer details form. This is to
mitigate slots being taken during the time it takes for the agent to
complete the customer details.
=> Move slot picker below customer details

config/database.yml
This ensures the correct pool size is configured in the production
environment.
=> Copy `default` configuration to production

app/models/bookable_slot.rb, config/initializers/working_hours.rb, spec/models/bookable_slot_spec.rb
Previously the end of the booking window was calculated at 8 weeks from the
time of request and didn't consider bank holidays. This change ensures we
also skip those days when calculating the end of the window.
=> Use 'business days' logic to calculate window

app/models/appointment.rb, app/models/user.rb, spec/models/appointment_spec.rb
Appointments should never switch organisations. This validation ensures
when the guider changes, they can only ever originate from the same
provider/organisation.
=> Ensure appointment organisations cannot change

app/models/appointment.rb, spec/models/appointment_spec.rb
When status changes back to pending from cancelled we need to check the
guider is not already taken, this means the underlying slot is free.
=> Check availability on status change

app/models/bookable_slot.rb, spec/models/bookable_slot_spec.rb, spec/requests/bookable_slots_api_spec.rb
TPAS need a 3 day grace period whereas the other providers can remain
the same. This change ensures the correct slots are deemed 'available'
within the correct, segmented grace periods.
=> Segment grace period for TPAS

app/models/bookable_slot.rb, spec/models/bookable_slot_spec.rb
Resource managers should see slots within the grace period but the
recent changes for segmentation caused a regression. This change ensures
resource managers can once again book short notice appointments.
=> Ensure grace period is respected

app/controllers/appointments_controller.rb
The `agent` was considered during the preview phase of allocation yet
was discarded at the actual creation phase. This could lead to
cross-organisation allocations. This change ensures we pass the `agent`
along in both instances.
=> Ensure `agent` is considered during allocation

app/models/bookable_slot.rb, app/models/user.rb
Previously the slots would be deleted in the past when a guider's
schedule was generated. This stops us being able to report on
availability retrospectively. This change ensures we only delete future
slots, and only in the case of guider deactivation.
=> Leave historical slots when generating

app/models/bookable_slot.rb
Only past slots should be left for reporting.
=> Ensure schedules are wiped forward

app/jobs/sms_cancellation_success_job.rb, spec/jobs/sms_cancellation_success_job_spec.rb
Includes the date attribute so it can be embedded into the SMS
cancellation success template.
=> Include date in SMS cancellation

app/models/appointment.rb, spec/models/appointment_spec.rb
Changes the SMS cancellation logic to ensure the appointment placed
first is cancelled when multiple pending appointments exist with a given
mobile phone number.
=> Cancel the oldest appointment first

app/controllers/appointments_controller.rb, app/models/appointment.rb, app/views/appointments/missing.html.erb, spec/features/appointment_permissions_spec.rb, spec/support/pages/edit_appointment.rb
This wasn't enforced explicitly before so when viewing duplicates,
sometimes a cross-organisation appointment would be linked and therefore
editable.
=> Enforce edit permission

app/controllers/api/v1/appointments_controller.rb, app/controllers/appointments_controller.rb, app/forms/api/v1/appointment.rb, app/jobs/accessibility_adjustment_notifications_job.rb, app/mailers/appointment_mailer.rb, app/models/appointment.rb, app/models/user.rb, app/views/appointment_mailer/accessibility_adjustment.html.erb, app/views/appointment_mailer/accessibility_adjustment.text.erb, app/views/appointment_mailer/reminder.text.erb, config/environments/development.rb, config/environments/production.rb, spec/jobs/accessibility_adjustment_notifications_job_spec.rb, spec/mailers/appointment_mailer_spec.rb, spec/mailers/previews/appointment_mailer_preview.rb, spec/requests/appointments_api_spec.rb
When a customer or agent specifies that they need an accessibility
adjustment to access their appointment we should notify those resource
managers associated with the appointment ahead of time.
=> Send accessibility alerts to resource managers

app/jobs/accessibility_adjustment_notifications_job.rb, app/mailers/appointment_mailer.rb, app/models/appointment.rb, spec/features/agent_manages_appointments_spec.rb, spec/jobs/accessibility_adjustment_notifications_job_spec.rb, spec/mailers/appointment_mailer_spec.rb, spec/requests/appointments_api_spec.rb
When the guider is from TPAS and we send an accessibility adjustment
alert we must send them to the supervisors mailbox, otherwise they're
sent to the resource managers as usual.
=> Alert supervisors mailbox for TPAS guiders

app/views/appointments/_personal_details_form.html.erb
Agents are still incorrectly attributing appointments to final nudge
calls. Making the labelling more prominent should help.
=> Improve final nudge labelling

app/views/layouts/application.html.erb, config/initializers/govuk_admin_template.rb
This would wrap for users with the administrator role, since the
provider dropdown was styled incorrectly and has recently increased in
width. The app title has changed to drop the 'Appointment', this matches
the other planners that also changed recently and has the useful effect
of freeing up some valuable horizontal real estate.
=> Improve layout of navigation bar

app/models/appointment.rb, spec/models/appointment_spec.rb
Changes logic to only enforce the presence of notes after the initial
change was introduced. This is to permit changes to appointments
pre-dating that time.
=> Only enforce notes after cut off date

app/models/appointment.rb, spec/features/sms_appointment_reminder_spec.rb
We should ensure that 'mobile' numbers are 'valid' UK mobile numbers
before including them in the SMS reminder candidate list.
Prior to this change there was no checks performed against the mobile
field and regular numbers as well as international numbers were creeping
through.
=> Ensure SMS candidates are correctly determined

app/forms/appointment_report.rb, spec/features/resource_manager_downloads_appointment_reports_spec.rb
Adds a column to the appointment report `summary_document_created` with
the value of 'Yes' or 'No' denoting the existence or absence of a
summary document.
=> Include a column for summary document existence

app/models/appointment.rb, spec/models/appointment_spec.rb
We had reports from guiders that some 10 digit numbers are callable in
UK so we need to relax the 11 digit validation.
=> Permit 10 character phone numbers

Gemfile, Gemfile.lock, app/controllers/api/v1/searches_controller.rb, app/lib/appointment_api_search.rb, app/serializers/appointment_search_serializer.rb, config/application.rb, config/environment.rb, config/initializers/gds_sso.rb, config/routes.rb, spec/lib/appointment_api_search_spec.rb, spec/requests/searches_api_spec.rb
When provided with a query (reference or partial match on name/email) we
return the appointments matching the given critera. The attributes:
reference, name and URL are serialized and returned as JSON.
=> Provide a simple search API for appointments

app/controllers/api/v1/searches_controller.rb, app/controllers/application_controller.rb, lib/tasks/confidentiality.rake, spec/lib/appointment_api_search_spec.rb
Previously this would trigger the creation of an activity that would
then be enqueued to pusher, meanwhile the activities are destroyed as
part of the redaction process and once the job is dequeued, the
underlying activity is gone so would cause an error.
=> Don't trigger audits after redacting

app/controllers/api/v1/appointments_controller.rb, app/controllers/appointments_controller.rb, app/forms/api/v1/appointment.rb, app/jobs/website_appointment_slack_pinger_job.rb, app/models/appointment.rb, app/views/appointments/_personal_details_form.html.erb, app/views/appointments/preview.html.erb, spec/factories/appointments.rb, spec/features/agent_manages_appointments_spec.rb, spec/features/agent_rebooks_appointments_spec.rb, spec/features/resource_manager_modifies_appointments_spec.rb, spec/requests/appointments_api_spec.rb, spec/support/pages/new_appointment.rb
Removes the final nudge provider from agent bookings and defaults to a
sensible value for customer bookings.
=> Remove final nudge fields

app/forms/drop_form.rb, spec/forms/drop_form_spec.rb
These were firing web hooks but are not handled internally by resource
managers, plus they appear as bounce activities against the associated
booking, thus confusing agents that may be viewing the activity feed. We
can just ignore these particular calls instead.
=> Ignore bounced accessibility adjustment emails

app/models/bookable_slot.rb, spec/requests/bookable_slots_api_spec.rb
Reverts guidance-guarantee-programme/telephone_appointment_planner#659
Going back to 48 hours due to ongoing COVID-19 mitigations.
=> Revert "Reduce grace period to effectively one day"

app/models/schedule.rb, spec/features/resource_manager_manages_schedules_spec.rb
This was requested by resource managers to aid the location of the most recent
schedule for a particular guider.
=> Reverse the ordering of guider schedules

app/controllers/api/v1/appointments_controller.rb, app/controllers/appointments_controller.rb, app/forms/drop_form.rb, app/forms/sms_cancellation.rb, app/jobs/appointment_cancelled_notifications_job.rb, app/jobs/appointment_created_notifications_job.rb, app/jobs/appointment_rescheduled_notifications_job.rb, app/lib/notifier.rb, app/mailers/appointment_mailer.rb, app/models/appointment.rb, app/models/user.rb, app/views/appointment_mailer/resource_manager_appointment_cancelled.html.erb, app/views/appointment_mailer/resource_manager_appointment_cancelled.text.erb, app/views/appointment_mailer/resource_manager_appointment_created.html.erb, app/views/appointment_mailer/resource_manager_appointment_created.text.erb, app/views/appointment_mailer/resource_manager_appointment_rescheduled.html.erb, app/views/appointment_mailer/resource_manager_appointment_rescheduled.text.erb, spec/factories/appointments.rb, spec/factories/users.rb, spec/features/resource_manager_manages_holidays_spec.rb, spec/forms/drop_form_spec.rb, spec/jobs/appointment_cancelled_notifications_job_spec.rb, spec/jobs/appointment_created_notifications_job_spec.rb, spec/jobs/appointment_rescheduled_notifications_job_spec.rb, spec/lib/notifier_spec.rb, spec/mailers/appointment_mailer_spec.rb, spec/mailers/previews/appointment_mailer_preview.rb, spec/requests/appointments_api_spec.rb, spec/requests/sms_cancellation_callback_spec.rb
Notify resource managers by email when an appointment has changed. Does not
apply to appointments pertaining to the TPAS organisation as they receive
realtime notifications.
=> Resource manager email notifications

app/controllers/processes_controller.rb, app/helpers/appointment_helper.rb, app/helpers/user_helper.rb, app/models/appointment.rb, app/models/processed_activity.rb, app/views/activities/_processed_activity.html.erb, app/views/appointments/edit.html.erb, app/views/appointments/search.html.erb, config/routes.rb, db/migrate/20200326124042_add_processed_at_to_appointments.rb, db/schema.rb, spec/factories/appointments.rb, spec/features/resource_manager_processes_an_appointment_spec.rb, spec/support/pages/edit_appointment.rb, spec/support/pages/search.rb
This marks an appointment as synchronised with casebook and only applies to
non-TPAS providers.
=> Allow non-TPAS users to 'process' appointments

lib/tasks/jobs.rake
This helps in the staging environment to keep a clean slate and aid the
onboarding effort for guiders that are channel-switching.
=> Add a task to delete schedules, slots and holiday

app/lib/redactor.rb, app/models/appointment.rb, lib/tasks/confidentiality.rake, spec/lib/redactor_spec.rb
Can redact a single appointment instance by `REFERENCE` or can now
redact all records older than 2 years for GDPR purposes.
=> Improve the redactor

app/models/appointment.rb, spec/models/appointment_spec.rb
This was previously erroring when the resource manager did not provide
an adhoc start date/time.
=> Ensure allocation does not error

app/models/bookable_slot.rb, spec/features/scheduled_reporting_summary_spec.rb, spec/requests/bookable_slots_api_spec.rb
This will ensure CAS can add slots that won't be immediately filled by
customer demand.
=> Temporarily exclude CAS slots from API respinse

app/controllers/appointments_controller.rb, app/forms/search.rb, app/models/appointment_search.rb, app/views/appointments/search.html.erb, spec/features/agent_searches_for_appointments_spec.rb, spec/features/resource_manager_processes_an_appointment_spec.rb, spec/models/appointment_search_spec.rb, spec/support/pages/search.rb
Defaults to all appointments for TPAS and shows filters for other
organisations. Defaults to 'no' for the organisations it applies to.
=> Add a filter for `processed` appointments

app/models/bookable_slot.rb, spec/models/bookable_slot_spec.rb
Previously this was allowing appointments to be created on the same,
given business day, as the timezone offset was not being applied.
=> Accommodate timezones for grace period

Gemfile, Gemfile.lock
This hasn't been needed since Rails 5 and now causes deprecation
messages in Rails 6.
=> Remove 12 factor gem

app/helpers/appointment_helper.rb, app/models/appointment.rb, app/views/appointments/edit.html.erb, spec/features/guider_edits_an_appointment_spec.rb, spec/support/pages/edit_appointment.rb
When the customer is unsure they have a DC pension we display a banner
to alert anyone viewing the appointment.
=> Display a banner for DC pension unsure customers

app/models/bookable_slot.rb, spec/models/bookable_slot_spec.rb
Effectively set the CoP to 9pm. This was 6:30pm previously and would
cause confusion among some delivery providers.
=> Extend close-of-play to 9pm

app/models/appointment_search.rb, spec/models/appointment_search_spec.rb
Directs to a single result regardless whether the appointment was
processed.
=> Return a single result regardless if processed

config/initializers/working_hours.rb
CAS have a handful of slots free on Saturday that would otherwise have
been skipped by the grace period.
=> Removing this holiday to shift CAS slots

app/jobs/customer_update_job.rb, app/models/drop_activity.rb, spec/jobs/customer_update_job_spec.rb
When the email attempted causes an SMTP error we ought to log an
activity so the agent or other owner gets an opportunity to correct the
underlying issue.
=> Log a 'drop activity' for invalid emails

app/assets/javascripts/modules/calendars/company.es6
Previously this logic only checked if a holiday overlapped a slot. For
example: if a slot for 13:50-14:50 existed and a holiday for the same
guider existed from 14:00-14:20, the slot would appear available. It now
checks whether both events overlap to ensure this doesn't happen.
Elsewhere where availability calculations are made by overlapping slots,
holidays and appointments were always unaffected as they use application
logic, not calendar JS logic.
=> Check slot overlaps holiday

app/controllers/api/v1/appointments_controller.rb, app/controllers/appointments_controller.rb, app/forms/api/v1/appointment.rb, app/views/appointments/_personal_details_form.html.erb, app/views/appointments/preview.html.erb, db/migrate/20200716092614_add_smarter_signposted_to_appointments.rb, db/schema.rb, spec/features/agent_manages_appointments_spec.rb, spec/requests/appointments_api_spec.rb, spec/support/pages/new_appointment.rb
This allows API clients, TPAS users or Pension Wise administrators to specify
when the given appointment was a 'smarter signposted' referral.
=> Smarter signposting

app/controllers/appointments_controller.rb, app/jobs/sms_appointment_reminder_job.rb, app/jobs/sms_cancellation_success_job.rb, app/models/appointment.rb, app/views/appointments/_personal_details_form.html.erb, app/views/appointments/preview.html.erb, app/views/shared/email/_appointment_details.html.erb, app/views/shared/email/_appointment_details.text.erb, db/migrate/20200924145011_add_bsl_video_to_appointments.rb, db/schema.rb, spec/features/agent_manages_appointments_spec.rb, spec/jobs/sms_appointment_reminder_job_spec.rb, spec/jobs/sms_cancellation_success_job_spec.rb, spec/mailers/appointment_mailer_spec.rb, spec/support/pages/new_appointment.rb
This lets the agent signal that this is going to be a BSL video based
appointment.
=> Add BSL video checkbox for appointments

app/helpers/appointment_helper.rb, app/models/user.rb, app/views/appointments/_personal_details_form.html.erb, spec/features/agent_manages_appointments_spec.rb
BSL video should only be visible to Lancs West and admins for
modification and to TP as readonly.
=> Restrict who can access BSL video

app/models/appointment.rb, app/views/appointments/preview.html.erb, spec/features/agent_manages_appointments_spec.rb, spec/models/appointment_spec.rb, spec/support/pages/preview_appointment.rb
A road safety warning appears in the preview stage when the customer has
a mobileish number against their appointment.
=> Add road safety warning

app/jobs/bsl_customer_exit_poll_job.rb, app/lib/notifier.rb, app/mailers/appointment_mailer.rb, app/models/bsl_customer_exit_poll_activity.rb, app/views/activities/_bsl_customer_exit_poll_activity.html.erb, app/views/appointment_mailer/bsl_customer_exit_poll.html.erb, app/views/appointment_mailer/bsl_customer_exit_poll.text.erb, spec/jobs/bsl_customer_exit_poll_job_spec.rb, spec/lib/notifier_spec.rb, spec/mailers/appointment_mailer_spec.rb, spec/mailers/previews/appointment_mailer_preview.rb
When a BSL appointment is marked complete, an email containing a link to
the exit poll will be scheduled for delivery in 24 hours.
=> Send an exit poll email to BSL customers

app/models/appointment.rb, spec/models/appointment_spec.rb
This was an oversight that was causing issues when moving third party
appointments that had an associated data subject age created when that
was possible, prior to the introduction of the data subject date of
birth and related validations.
=> Don't require a data subject dob if age present

app/lib/scheduled_reporting_summary.rb, db/migrate/20210216104738_add_two_week_availability_to_scheduled_reporting_summaries.rb, db/schema.rb, spec/factories/bookable_slots.rb, spec/features/scheduled_reporting_summary_spec.rb
Adds the two week availability flag for providers to accompany the
existing four week availability flag.
=> Calculate two week availability for reporting

app/controllers/duplicates_controller.rb, app/helpers/appointment_helper.rb, app/models/appointment.rb, app/models/email_lookup.rb, app/models/provider.rb, app/presenters/duplicate_presenter.rb, app/views/appointments/edit.html.erb, app/views/duplicates/index.html.erb, config/routes.rb, db/migrate/20210223123516_create_email_lookups.rb, db/schema.rb, spec/features/guider_views_duplicate_appointments_spec.rb, spec/support/pages/duplicate_appointments.rb
Moves the duplicates off the edit screen and into a separate page for
easier viewing by an agent.
=> Improve duplicates display

app/presenters/audit_presenter.rb, spec/features/appointment_changes_spec.rb, spec/support/pages/appointment_changes.rb
If a formatter exists for a given key we can use this to format the
value presented to the user. For example, a guider ID of 1 becomes the
actual guider's name. Similarly the agent and also the status ordinal.
=> Format common fields when displaying changes

db/migrate/20210311122614_add_unique_check_for_appointments.rb, db/schema.rb, spec/features/guider_views_their_activities_spec.rb, spec/features/notifications_spec.rb, spec/features/resource_manager_modifies_appointments_spec.rb, spec/forms/api/v1/appointment_spec.rb, spec/support/pages/edit_appointment.rb
If two customers contend for the same slot within the same second it can
cause a race between the allocation of the slot and the creation of the
appointment. This is especially common when a slot is the earliest
available in the current booking window, thus heavily contended.
=> Stop a race when placing appointments via the API

app/lib/where_you_heard.rb
Moves these options down the order so they are still visible for
existing appointments but less prominent for new appointments.
=> Reposition now redundant options

db/migrate/20210421133500_add_date_criterion_to_unique_appointments_check.rb, db/schema.rb, spec/forms/api/v1/appointment_spec.rb
Allows preexisting 'duplicate' appointments to exist before today. Any
newly created 'duplicate' appointments will be disallowed in future.
=> Only apply uniqueness after cut-off

app/jobs/adjustment_notifications_job.rb, app/jobs/application_job.rb, app/jobs/appointment_cancelled_notifications_job.rb, app/jobs/appointment_rescheduled_notifications_job.rb, spec/jobs/adjustment_notifications_job_spec.rb, spec/jobs/appointment_cancelled_notifications_job_spec.rb, spec/jobs/appointment_rescheduled_notifications_job_spec.rb
Rather than send to individual resource managers, we can send these
email notifications to the given CAS alias.
=> Send to CAS alias when necessary

app/forms/api/v1/appointment.rb, spec/forms/api/v1/appointment_spec.rb
There was an issue where incompatible versions did not function
correctly.
=> Default `lloyds_signposted` to false

app/assets/javascripts/modules/calendars/appointment-availability.es6, app/assets/javascripts/modules/lloyds-signposter.es6, app/controllers/appointments_controller.rb, app/controllers/bookable_slots_controller.rb, app/models/appointment.rb, app/models/bookable_slot.rb, app/models/user.rb, app/views/appointments/_availability_calendar.html.erb, app/views/appointments/_schedule_form.html.erb, app/views/appointments/new.html.erb, app/views/appointments/preview.html.erb, app/views/appointments/reschedule.html.erb, config/routes.rb, spec/features/agent_manages_appointments_spec.rb, spec/support/pages/new_appointment.rb
Grants the permitted users the rights to refer an appointment from the
LLoyds Banking Group. Selecting the option will filter the availability
down to the correctly enrolled guiders/providers. Placing an appointment
flags for Lloyds as per the customer bookings.
=> Allow agents to book Lloyds signposted referrals

app/controllers/bookable_slots_controller.rb, spec/features/resource_manager_reschedules_an_appointment_spec.rb, spec/support/pages/reschedule_appointment.rb
Resource managers should be able to book appointments earlier than the
grace period and a recent change introduced a regression that this will
fix.
=> Ensure reschedules respect grace period override

app/views/appointments/edit.html.erb
These were previously displayed as large banners and took up lots of
space, especially when multiple attributes were present on a given
appointment.
=> Display labels for appointment attributes

app/controllers/appointments_controller.rb, spec/models/bookable_slot_spec.rb
Ensures slots are allocated correctly for rescheduling. This will be
revisited shortly and tidied up but for now this fixes the underlying
issue.
=> Ensure slots are correctly allocated

app/models/appointment.rb, app/models/user.rb, spec/models/appointment_spec.rb, spec/requests/appointments_api_spec.rb
This validation will ensure upon creation that an appointment flagged
for LBGPTL can never be allocated to guiders outside of the CITA
organisations.
=> Ensure LBGPTL appointments have valid guiders

.travis.yml, Gemfile, Gemfile.lock, spec/features/guider_views_appointments_spec.rb, spec/features/notifications_spec.rb, spec/features/resource_manager_manages_guiders_spec.rb, spec/features/resource_manager_manages_holidays_spec.rb, spec/features/resource_manager_manages_schedules_spec.rb, spec/features/resource_manager_modifies_appointments_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb, spec/support/chrome.rb, spec/support/poltergeist.rb, spec/support/user_helpers.rb, spec/support/webmock.rb
PhantomJS has been dead for a long time and for various reasons we were
still pinned to old versions of the supporting testing libraries. This
change begins the migration towards chrome-driver instead. Some of the
specs are still tagged with the poltergeist driver, these can be
resolved as time goes by.
=> Begin switch to webdrivers

app/models/bookable_slot.rb, spec/models/bookable_slot_spec.rb
During these given dates TPAS have requested alterations to the grace
period to aid the booking process in the first week of availability.
=> DD grace period alterations

app/controllers/appointments_controller.rb, app/models/appointment.rb, app/views/appointments/_personal_details_form.html.erb, app/views/appointments/preview.html.erb, db/migrate/20211123180605_add_small_pots_to_appointments.rb, db/schema.rb, spec/features/agent_manages_appointments_spec.rb, spec/features/booking_due_diligence_appointments_spec.rb, spec/support/pages/new_appointment.rb
TPAS users can specify a small pots appointment option otherwise it
defaults to false. This cannot be specified in combination with due
diligence appointments.
=> Add small pots option for TPAS users

app/models/appointment.rb, spec/requests/appointments_api_spec.rb
This was being validated against and being determined 'too soon' for
bookings despite being within the permitted grace period.
=> Resolve production bug in PSG grace periods

app/assets/stylesheets/components/_calendars.scss
Lightens and stripes PSG appointments with the same shade of purple that
would usually apply to future appointments, to make them more easily
differentiated in the various calendar views.
=> Differentiate completed PSG appointments

lib/tasks/export.rake
Adds the field to discriminate between Pension Wise and PSG appointments
for the reporting platform ingestion.
=> Add further requested fields to blob exports

app/controllers/api/v1/bookable_slots_controller.rb, app/models/bookable_slot.rb, spec/requests/bookable_slots_api_spec.rb
Allows clients to specify a specific day for slots to limit the data
that is retrieved. By default we can just return the slots for the
window.
=> Improve slots API

spec/features/resource_manager_manages_holidays_spec.rb
There is a strange timing issue in this spec that can be supressed by
guarding against jquery being present in the window.
=> Guard against jquery being undeclared

db/migrate/20220515124400_add_schedule_type_indices.rb, db/schema.rb
Adds indexes across some tables/columns that heroku postgresql stats are
reporting slower performance. The columns specified underpin many
predicates across the system.
=> Add several missing indices

db/migrate/20220701101008_alter_unique_check_for_appointments.rb, db/schema.rb
This needed widening to allow duplicates across ineligible statuses too.
=> Alter unique index to permit ineligibles too

app/jobs/bsl_customer_exit_poll_job.rb, app/views/activities/_bsl_customer_exit_poll_activity.html.erb, spec/jobs/bsl_customer_exit_poll_job_spec.rb
For BSL customers an exit poll is sent 24 hours after their appointment
is marked completed. This change will send an SMS version of the exit
poll if a mobile number is present, otherwise it will fall back on the
email version of the exit poll.
=> Send an SMS customer exit poll when possible

app/controllers/appointments_controller.rb, app/models/appointment.rb, app/models/bookable_slot.rb, app/views/appointments/edit.html.erb, app/views/appointments/preview.html.erb, spec/features/agent_manages_appointments_spec.rb, spec/features/guider_edits_an_appointment_spec.rb, spec/features/resource_manager_reschedules_an_appointment_spec.rb, spec/support/chrome.rb
When the TPAS agent checks the internal availability, this preference
must persist all the way through to allocation of the slot.
=> Ensure allocation respects internal/external

app/lib/notifier.rb, spec/lib/notifier_spec.rb, spec/support/chrome.rb
We noticed changes to the consent email wouldn't trigger new consent form
emails to be sent.
=> Allow consent email changes to trigger new email

app/controllers/appointments_controller.rb, app/jobs/printed_confirmation_job.rb, app/lib/notifier.rb, app/models/appointment.rb, app/models/printed_confirmation_activity.rb, app/presenters/printed_confirmation_presenter.rb, app/views/activities/_printed_confirmation_activity.html.erb, spec/features/agent_manages_appointments_spec.rb, spec/jobs/printed_confirmation_job_spec.rb, spec/lib/notifier_spec.rb
Adds print confirmations for new appointments and reschedules via
notify. This will ultimately replace the batch process for printing once
it's brought in-house.
=> Printed confirmations via Notify

app/models/appointment.rb, spec/models/appointment_spec.rb
This resolves an issue occuring currently for TPAS agents when
attempting to alter an existing appointment belonging to an outside
organisation.
=> Only validate when the status changes

app/models/appointment_search.rb, app/views/appointments/search.html.erb, spec/features/resource_manager_reschedules_an_appointment_spec.rb
This is a performance nightmare as it currently stands. We can
short-circuit a lot of queries straight to a simple where clause when
the query is just an appointment reference. Also, we can bound the
result set when no date range is specified, so we're not performing text
scans across the whole dataset.
=> Improve searching

app/models/appointment.rb, spec/jobs/printed_confirmation_job_spec.rb
This didn't correctly guard against rare instances where PSG
appointments could potentially trigger printed confirmation letters from
notify.
=> Ensure printed confirmation attempts PW only

app/assets/javascripts/modules/calendars/appointment-availability.es6, spec/features/agent_manages_appointments_spec.rb, spec/features/agent_rebooks_appointments_spec.rb, spec/features/booking_due_diligence_appointments_spec.rb, spec/features/resource_manager_reschedules_an_appointment_spec.rb, spec/support/pages/new_appointment.rb, spec/support/pages/reschedule_appointment.rb
Temporarily hide this expensive view while we work on a solution to
timeout and slow request issues.
=> Hide week view from booking calendar

app/models/appointment_search.rb, app/views/appointments/search.html.erb
This was requested by Pension Ops staff as it better matches the regular
window of bookings they operate under.
=> Widen search range to 6 months

app/models/bookable_slot.rb, spec/features/agent_manages_appointments_spec.rb, spec/features/guider_views_appointments_spec.rb, spec/models/bookable_slot_spec.rb, spec/requests/bookable_slots_api_spec.rb
Pension ops have requested a temporary increase to their grace period to handle an influx of appointments and cancellations. Some tests are marked to skip since they don't make sense with this change and need rethinking. They don't affect POPS so can remain for now.
=> Bump Pension Ops grace period to 5 days

app/models/appointment.rb, app/models/bookable_slot.rb, spec/models/appointment_spec.rb, spec/requests/bookable_slots_api_spec.rb
Increases these two in lockstep to ensure there is Pension Wise availability during this particularly busy period.
=> Expand booking and slot generation window

app/models/appointment.rb, spec/lib/notifier_spec.rb
This event should not trigger customer notifications. Adding the column to the non-notify list satisfies this.
=> Do not trigger notifications on 'reschedule'

app/jobs/customer_update_job.rb, app/mailers/appointment_mailer.rb, spec/lib/notifier_spec.rb
These continually retry when the recipient is unlisted in MailGun's allow-list and we don't want them to queue indefinitely.
=> Discard email failures for MailGun sandboxing

app/controllers/mail_gun/drops_controller.rb, app/forms/drop_form.rb, spec/requests/mailgun_drop_notification_spec.rb
Upgraded to new webhook format (JSON) as legacy webhooks (regular form payload) have been discontinued
=> Convert payload to mailgun webhook JSON

spec/features/guider_views_appointments_spec.rb
This was failing at times due to the order of the bookable slots being non-deterministic.
=> Order the slots before checking them

app/controllers/mail_gun/drops_controller.rb, spec/requests/mailgun_drop_notification_spec.rb
There are cases where these nested values are not present in the payload from mailgun. In these cases currently an error is raised but instead we can try and parse the payload and allow the `DropForm` validation to exclude the message when necessary attributes are missing.
=> Access the `event-data` nested hashes better

Gemfile, Gemfile.lock, app/lib/summary_document_api.rb, app/lib/web_hook.rb
The standard Net::HTTP adapter causes 'too many open files' during tests and the webmock configuration to counter this also doesn't work as expected. We can just switch to a more reliable adapter instead.
=> Switch adapters to counter webmock errors

config/sidekiq.yml
We sometimes see redis connections being exhausted.
=> Reduce staging sidekiq concurrency

app/forms/drop_form.rb, spec/forms/drop_form_spec.rb
These notifications are not longer an issue since the sender domains were added to their allow list
=> Alerts for bt internet were removed 

app/assets/javascripts/modules/date-range-picker.es6, app/views/appointments/search.html.erb
This needed tweaking to ensure the correct dates are selected and persisted through to the underlying textbox when hitting the 'apply' button.
=> Correct configuration for date ranges

app/forms/api/v1/appointment.rb, app/models/bookable_slot.rb, spec/models/bookable_slot_spec.rb, spec/requests/appointments_api_spec.rb
Prior to this change the allocation of slots was not respecting the variable booking window per provider. For example, in the case of TPAS/ops, they could have 10 slots for the given `start_at` and this would outweigh the slot that would usually be allocated by a single instance of matching date/time despite being outside of their regular booking window.
=> Ensure allocation respects booking window

.travis.yml, app/models/user.rb, spec/factories/users.rb, spec/requests/sso_push_for_disabling_guider_permissions_spec.rb
When a guider is suspended or has the 'guider' permission removed in signon, there are some cases where their availability continues and errant appointments are created with their slots. This change ensures that when a guider is suspended, or has their 'guider' permission removed, a blank schedule is created from the current day which has the effect of removing their future availability.
When they are reinstated, their resource manager can create new availability schedules as they see fit.
=> Remove guider's availability when SSO suspended

app/controllers/print_confirmations_controller.rb, app/jobs/printed_confirmation_job.rb, app/models/activity.rb, app/models/appointment.rb, app/models/printed_confirmation_failed_activity.rb, app/views/activities/_printed_confirmation_failed_activity.html.erb, app/views/appointments/edit.html.erb, config/routes.rb, spec/features/agent_manages_appointments_spec.rb, spec/jobs/printed_confirmation_job_spec.rb, spec/support/pages/edit_appointment.rb
When these fail due to errant address elements, the appointment record is not updated. This means the owning agent/guider has no knowledge or opportunity to correct the issues. This change ensures they can at least see that GOVUK notify determined that the address was invalid.
=> Create a failure activity for postal letters

app/jobs/customer_update_job.rb, spec/jobs/customer_update_job_spec.rb
There was an edge case where the appointment could be in a non-pending status and the customer would still receive an email informing them their appointment was updated, when an agent or other individual changed the underlying appointment. This change ensures we guard against this eventually by always checking whether the appointment is still in the pending phase.
=> Ensure customer update email sent correctly

app/views/consents/create.html.erb, app/views/shared/email/_money_helper.html.erb, app/views/shared/email/_money_helper.text.erb
Changes the office address to the new Bedford location in both the customer emails and the PDF third-party consent form.
=> Money Helper address change

app/jobs/sms_appointment_reminder_job.rb, app/models/sms_reminder_failure_activity.rb, app/views/activities/_sms_reminder_failure_activity.html.erb, spec/jobs/sms_appointment_reminder_job_spec.rb
If notify cannot deliver the SMS we create an activity and assign the guider as the owner.
=> Log an activity when SMS reminder fails

app/assets/javascripts/modules/calendars/allocations.es6, app/helpers/user_helper.rb, app/models/appointment.rb, app/serializers/user_serializer.rb, app/views/users/index.html.erb, spec/models/appointment_spec.rb
This will be redundant once the guiders are legitimate guiders and not the 'fake' PSG scheduled guiders.
=> Remove PSG reallocation validation

app/models/appointment.rb, app/views/appointments/edit.html.erb, spec/models/appointment_spec.rb
This change allows anyone to create summary documents within their organisation. Pension Ops can create across all organisations.
=> Broaden summary document button visibility

app/models/user.rb
This scope is used to determine which resource managers to notify, wherever it's used. `active` doesn't make sense for resource managers since unless they have the `guider` permission, they won't appear in a screen where this flag could be toggled. I think it was included historically just to maintain parity with how guiders are retrieved, but this doesn't make sense.
=> Don't scope resource managers to `active`

app/views/consents/create.html.erb
This brings the form down to a single page.
=> Remove redundant paragraph spacing

app/views/appointments/_personal_details_form.html.erb
This stops some dud entries being given and uses the right keyboard on mobile devices.
=> Email consent should be an email field

app/controllers/appointments_controller.rb, app/models/appointment.rb, app/views/appointments/_personal_details_form.html.erb, app/views/appointments/edit.html.erb, app/views/appointments/preview.html.erb, db/migrate/20240326090221_add_welsh_to_appointments.rb, db/schema.rb, spec/features/agent_manages_appointments_spec.rb, spec/features/agent_searches_for_appointments_spec.rb, spec/features/booking_due_diligence_appointments_spec.rb, spec/support/pages/new_appointment.rb
This is managed by anyone for their own organisation but is disabled when viewing another organisation's appointment(s). Does not trigger changed notifications.
=> Add Welsh language appointments flag

app/lib/casebook/presenters/create.rb, spec/lib/casebook/api_spec.rb, spec/lib/casebook/presenters/create_spec.rb, spec/lib/casebook/presenters/reschedule_spec.rb
This helps match casebook's expectations.
=> Strip non-numeric characters for mobile payloads

app/jobs/reschedule_casebook_appointment_job.rb
In the case of appointments that were not originally pushed to Casebook, we mustn't attempt to 'reschedule' them via Casebook as it will cause a 404 error response since the TAP appointment does not hold the Casebook appointment ID.
=> Guard against Casebook reschedule attempts

app/models/appointment.rb
Rather than attempting to match the appointment day, match on the DoB too.
=> Alter duplicate checks to match DoB

app/models/appointment.rb, spec/models/appointment_spec.rb
When the job executes in the context of the transaction there is a timing issue meaning the cancellation status will not yet be persisted, causing the casebook cancellation job to short-circuit due to the `Appointment#cancelled?` evaluating false.
=> Ensure Casebook cancellation occurs correctly

app/lib/notifier.rb, spec/lib/notifier_spec.rb
This shouldn't occur as the customer only needs to be informed when the appointment date/time changes, not when this remains the same but the guider has changed eg reallocation.
=> Don't send printed confirmation of reallocation

app/assets/javascripts/modules/secondary-status.es6, app/controllers/appointments_controller.rb, app/models/appointment.rb, app/views/appointments/_personal_details_form.html.erb, db/migrate/20240530142914_add_cancelled_via_to_appointments.rb, db/schema.rb, spec/features/agent_manages_appointments_spec.rb, spec/features/appointment_changes_spec.rb, spec/models/appointment_spec.rb, spec/support/pages/edit_appointment.rb
When the appointment is marked with the secondary status 'cancelled prior to appointment' we want to track the channel the customer used to cancel their appointment.
=> Add cancellation via option

app/controllers/api/v1/appointments_controller.rb, app/controllers/api/v1/nudge_appointments_controller.rb, app/controllers/appointments_controller.rb, app/jobs/application_job.rb, app/lib/notifier.rb, app/mailers/appointment_mailer.rb, app/models/appointment.rb, app/views/appointment_mailer/potential_duplicates.html.erb, app/views/appointment_mailer/potential_duplicates.text.erb, spec/lib/notifier_spec.rb, spec/mailers/appointment_mailer_spec.rb, spec/models/appointment_spec.rb
This changes how these notifications were delivered. They're no longer part of the broader adjustments notifications and now are a separate email notification that occurs at any given time during the appointment lifecycle and are only ever received by the ops mailbox alias.
=> Send a separate email for potential duplicates

app/assets/javascripts/modules/secondary-status.es6, spec/features/cancelled_via_regression_spec.rb
This was a subtle bug that could occur when the agent chooses a particular combination of primary and secondary statuses.
=> Ensure primary status changes hide cancel reasons

app/jobs/casebook_job.rb
We had a couple instances of these due to Casebook suffering ephemeral network issues. With this mitigation the jobs will retry a few times on an exponential backoff until successful, otherwise an error will be logged as usual.
=> Retry on network timeouts

app/lib/notifier.rb, spec/lib/notifier_spec.rb
There were some cases where duplicate notifications were being sent and causing confusion. Eg when an appointment was cancelled by an agent it was still notifying the relevant resource managers that duplicates were present. This change ensures duplicate notifications are only triggered by pending appointments.
=> Only send duplicate notifications on pending

app/models/appointment_search.rb, app/views/appointments/search.html.erb, spec/models/appointment_search_spec.rb
Removes guider name as a criteria when searching for appointments as it causes false-positives in the results and has been requested by Pensions Ops.
=> Do not search across guider name

db/migrate/20240901141920_alter_duplicate_appointments_index.rb, db/schema.rb
There are older records that cause problems with this index predicates so we can just exclude those instead.
=> Exclude newer appointments from these checks

app/views/appointments/preview.html.erb, app/views/shared/email/_appointment_details.html.erb, app/views/shared/email/_appointment_details.text.erb, spec/features/agent_manages_appointments_spec.rb, spec/mailers/appointment_mailer_spec.rb
Remove the ambiguity around appointment durations.
=> Simplify appointment duration copy

app/models/appointment.rb, spec/models/appointment_spec.rb
This should only be triggered when the `start_at` for the appointment was altered. This happens during creation and when the appointment is rescheduled. The prior behaviour was blocking online cancellations for appointments that were booked before the booking window reduction and were occuring past the now-valid booking window.
=> Don't trigger booking window validations needless

app/presenters/duplicate_presenter.rb, app/views/appointments/preview.html.erb, app/views/duplicates/index.html.erb, spec/features/agent_manages_appointments_spec.rb, spec/support/pages/preview_appointment.rb
When the agent is previewing an appointment we now display any duplicates matching the usual logic of first and last name, DoB and the pending status.
=> Show potential duplicates on preview page

app/jobs/summary_document_check_job.rb, app/lib/notifier.rb, app/mailers/appointment_mailer.rb, app/views/appointment_mailer/guider_summary_document_missing.html.erb, app/views/appointment_mailer/guider_summary_document_missing.text.erb, spec/jobs/summary_document_check_job_spec.rb, spec/lib/notifier_spec.rb, spec/mailers/appointment_mailer_spec.rb, spec/mailers/previews/appointment_mailer_preview.rb
When the appointment is completed, a check is scheduled or 24hrs that will notify the guider when the appointment was not yet summarised.
=> Send alerts after 24 hours without summarising

app/controllers/api/v1/cancels_controller.rb, app/forms/api/v1/appointment_cancellation.rb, app/models/appointment.rb, db/migrate/20241023134101_add_other_reason_to_appointments.rb, db/schema.rb, spec/forms/api/v1/appointment_cancellation_spec.rb, spec/requests/cancellations_api_spec.rb
The customer can now specify a further free-text reason when they follow the cancellation self-serve journey and specify 'other' as their reason.
=> Allow cancellation reasons to be expanded

.rubocop.yml, app/lib/casebook/api.rb, app/lib/casebook/push.rb, app/lib/casebook/reschedule.rb, app/lib/casebook/response.rb, app/models/appointment.rb, app/views/activities/_casebook_processed_activity.html.erb, spec/lib/casebook/api_spec.rb, spec/lib/casebook/push_spec.rb, spec/lib/casebook/reschedule_spec.rb, spec/models/appointment_spec.rb
This was requested by CITA as it helps them find the matching appointment in casebook without using DOB and other criteria from the underlying appointment.
=> Include casebook case reference in activity feed

Gemfile, Gemfile.lock, lib/tasks/holidays.rake, spec/features/resource_manager_modifies_appointments_spec.rb
CAS have requested that all guiders have an allocated holiday entry for every Saturday throughout 2025.
=> Block all Saturdays throughout 2025 for CAS

app/models/bookable_slot.rb, spec/requests/bookable_slots_api_spec.rb
This covers the increase in booking window and the generation range for bookable slots.
=> Broaden PSG booking window to 12 weeks

app/models/appointment.rb, spec/models/appointment_spec.rb
This wasn't taking into account the differences between the end of the booking window for PSG and PW respectively.
=> Ensure booking window validation is respected

app/controllers/releases_controller.rb, app/models/release.rb, app/views/releases/index.html.erb, app/views/shared/_navigation.html.erb, config/routes.rb, db/migrate/20241125195323_create_releases.rb, db/schema.rb
Adds a date ordered list of released changes with plain text summaries. This is very basic for now and entries will be made from the console.
=> Add change log page

app/controllers/appointments_controller.rb, app/controllers/bookable_slots_controller.rb, app/helpers/application_helper.rb, app/helpers/user_helper.rb, app/models/appointment.rb, app/models/bookable_slot.rb, app/models/user.rb, app/views/appointments/_availability_calendar.html.erb, spec/features/agent_rebooks_appointments_spec.rb
This change permits non-ops resource managers to rebook externally. When they see the rebooking calendar they're automatically offered external slots only. They have to choose internal explicitly to see their own slots.
This is currently in the proof-of-concept phases and may change.
=> Non-ops resource managers can rebook external

app/lib/notifier.rb, spec/lib/notifier_spec.rb
There was a flaw in this logic that meant all resource managers were excluded from change notifications, other than ops appointments.
=> Ensure resource managers are notified correctly

app/controllers/api/v1/bookable_slots_controller.rb, spec/requests/bookable_slots_api_spec.rb
We want to capture these instances to understand how often this occurs for customers when they request a stale day from the cached frontend calendars.
=> Log when empty slots are returned for a day

app/models/bookable_slot.rb
Querying over the `end_at` is unnecessary and confuses the query planner. We can query over the `start_at` boundaries instead and this is much faster.
=> Improve logic for querying bookable slots

.travis.yml, app/models/bookable_slot.rb, db/migrate/20241215181148_add_ts_range_indices_for_appointments_holidays_bookable_slots.rb, db/schema.rb
`OVERLAPS` barely ever makes use of indices. Conversion to the native `TSRANGE` and comparisons of such are hugely more performant.
=> Use `TSRANGE` types for optimisations

app/assets/javascripts/modules/calendars/appointment-availability.es6, spec/features/agent_manages_appointments_spec.rb, spec/features/agent_rebooks_appointments_spec.rb, spec/features/booking_due_diligence_appointments_spec.rb, spec/features/resource_manager_reschedules_an_appointment_spec.rb, spec/support/pages/new_appointment.rb, spec/support/pages/reschedule_appointment.rb
This reverts commit c1b457befe5a0ddf5d7f02184dcc278fa6734d00.
This can be restored now as the calendar performs much better.
=> Revert "Hide week view from booking calendar"

app/models/appointment.rb, spec/features/sms_appointment_reminder_spec.rb, spec/models/appointment_spec.rb
Allows other mobileish numbers through for SMS messaging. When the phone or mobile begins with any of 07, +447 or 00447 then it is included in SMS confirmations, reminders and other comms.
=> Be more permissive with mobile numbers

app/lib/casebook/presenters/reschedule.rb, app/models/appointment.rb, spec/lib/casebook/presenters/reschedule_spec.rb
When a guider is reallocated and the appointment was pushed to casebook, we will automatically send a reschedule call to the casebook API. However, we don't provide the mandatory `reschedule_status`. We can safely infer this as `office_rescheduled`.
=> Infer rescheduling reason when missing

app/controllers/activities_controller.rb
This is in some cases querying across the whole table for particular individuals. These aren't considered timely after a month or so so limiting them this way is a quick fix.
=> Limit the high-priority activities

db/migrate/20250124115245_add_ts_range_guider_id_index_to_appointments.rb, db/schema.rb
This drops the overall runtime for this query (using the example parameters I was given) from around 11 seconds to less than 0.2 of a second.
=> Add missing index for rebooking query

app/forms/sms_cancellation.rb, app/models/sms_message_activity.rb, app/views/activities/_sms_message_activity.html.erb, spec/requests/sms_cancellation_callback_spec.rb
Logs inbound SMS replies from customers on the appointments they're
associated with. They'll appear in the activity feed in realtime.
=> Log inbound SMS replies

app/jobs/bsl_customer_exit_poll_job.rb, app/jobs/concerns/sms_failure_recordable.rb, app/jobs/sms_appointment_confirmation_job.rb, app/jobs/sms_appointment_reminder_job.rb, app/jobs/sms_cancellation_success_job.rb, app/jobs/sms_failure_notifications_job.rb, app/mailers/appointment_mailer.rb, app/models/sms_failure_activity.rb, app/views/activities/_sms_failure_activity.html.erb, app/views/activities/_sms_reminder_failure_activity.html.erb, app/views/appointment_mailer/resource_manager_sms_failure.html.erb, app/views/appointment_mailer/resource_manager_sms_failure.text.erb, db/migrate/20250202131803_rename_sms_reminder_failure_activities.rb, db/schema.rb, spec/jobs/sms_appointment_reminder_job_spec.rb, spec/jobs/sms_failure_notifications_job_spec.rb, spec/mailers/appointment_mailer_spec.rb, spec/mailers/previews/appointment_mailer_preview.rb
These jobs will also track SMS delivery failures and record an activity 
against the appointment in question. These failures will also be notifed to
owning resource managers via email.
=> Configure SMS jobs to track failures

app/controllers/api/v1/appointments_controller.rb, app/controllers/appointments_controller.rb, app/forms/api/v1/appointment.rb, app/helpers/appointment_helper.rb, app/models/appointment.rb, app/views/appointments/_personal_details_form.html.erb, app/views/appointments/preview.html.erb, db/migrate/20250120124209_add_attended_digital_to_appointments.rb, db/schema.rb, spec/features/agent_manages_appointments_spec.rb, spec/features/booking_due_diligence_appointments_spec.rb, spec/models/appointment_spec.rb, spec/rails_helper.rb, spec/requests/appointments_api_spec.rb, spec/support/pages/new_appointment.rb
Similar to the API change, regular phone appointments will display an 
option for the customer to specify whether they have previously completed a
PWD appointment.
=> Bookings can specify PWD appointment attended

app/models/appointment.rb, spec/models/appointment_spec.rb
This was affecting some older appointments created prior to the
introduction of this particular validation.
=> Add cut-off for eligibility reasons pre 10/02/25

spec/features/booking_due_diligence_appointments_spec.rb, spec/features/guider_edits_an_appointment_spec.rb, spec/features/resource_manager_manages_holidays_spec.rb, spec/features/resource_manager_modifies_appointments_spec.rb, spec/features/resource_manager_sorts_guiders_spec.rb, spec/support/pages/edit_appointment.rb, spec/support/pages/holidays.rb, spec/support/pages/search.rb, spec/support/pages/sort_guiders.rb
In many places we assert on model data instead of observable page elements.
This causes some subtle timing issues and should be avoided for simplicity.
=> Alterations to assert on page output

app/jobs/appointment_status_reminder_job.rb, app/mailers/appointment_mailer.rb, app/models/appointment.rb, app/views/appointment_mailer/guider_status_reminder.html.erb, app/views/appointment_mailer/guider_status_reminder.text.erb, db/migrate/20250312153811_add_status_reminder_sent_to_appointments.rb, db/schema.rb, spec/jobs/appointment_status_reminder_job_spec.rb, spec/mailers/appointment_mailer_spec.rb, spec/mailers/previews/appointment_mailer_preview.rb, spec/models/appointment_spec.rb
Guiders will be reminded by email when the status remains pending after
24 hours since the appointment was delivered.
=> Send reminders when appointments remain pending

app/forms/sms_cancellation.rb, app/models/appointment.rb, spec/models/appointment_spec.rb
There have been incidents where customers replied to their reminder SMS
messages with the 'cancel' keyword but received a cancellation failure
SMS in response. These are due to normalisation issues occurring between
us and Notify. For example, when a customer's number is stored as
'+447...' the `source_number` we receive back from Notify is `447...'
thus the appointment for cancellation cannot be found. This change will
attempt to find the number by many sensible variants instead.
=> Find appointments with normalised numbers

spec/support/chrome.rb
This nerfs a bunch of timing issues caused by changes in the most recent
chromedriver on macos.
=> Disable headless backgrounding stuff

app/jobs/due_diligence_reference_number_job.rb, spec/jobs/due_diligence_reference_number_job_spec.rb
This wasn't configured correctly and so wasn't ensuring that the
reference number in rare cases when it generates a clash was not being
persisted.
=> Ensure the reference number job re-runs

app/views/appointments/edit.html.erb, app/views/my_appointments/show.html.erb, spec/features/guider_edits_an_appointment_spec.rb, spec/support/pages/edit_appointment.rb
Some guiders get confused when viewing appointments and make calls that are scheduled for other days. Adding prominent banners to appointments when they're viewed by guiders - denoting whether the appointment is scheduled for today or other days will be helpful.
=> Show scheduling banners for guiders
