guidance-guarantee-programme/telephone_appointment_planner

.gitignore
.travis.yml
Gemfile
Gemfile.lock
bower.json
config/application.rb
package.json

- adding package.json to install babel and eslint
- running npm install on travis
- enable sprockets-es6
- adding basic bower.json

Adding the ability to write es6

---

app/views/layouts/application.html.erb

Add missing link for managing tags

---

app/assets/javascripts/calendar.es6
app/assets/javascripts/multi-checkbox.es6
app/assets/javascripts/sortable-list.es6
app/views/layouts/application.html.erb
app/views/slot_ranges/_form.html.erb
app/views/users/index.html.erb
spec/features/slot_ranges_spec.rb

- now use the concept of data-module attribute to trigger the
initalising of a JS module
- Ensure all the JS is in assets/javascripts folder
- Created multi-checkbox module which can be potentially reuseable
- Created sortable-list module which uses ListJs to sort/filter
a list of 'things' - used on guiders list

Improve initialising of JS modules for project

---

app/views/groups/index.html.erb

- added caption to improve accessibility
- pushed actions to right side of table

Minor UI alteration to the list of groups

---

app/views/groups/index.html.erb
app/views/users/edit.html.erb
app/views/users/index.html.erb

Adding iconography to improve the UI

Adding Glyphicons to the UI

---

app/controllers/schedules_controller.rb
app/models/schedule.rb
app/views/schedules/_form.html.erb
spec/factories/schedules.rb
spec/features/roles_spec.rb
spec/features/schedules_spec.rb
spec/models/schedule_spec.rb
spec/support/pages/edit_schedule.rb
spec/support/pages/new_schedule.rb

I am in the process of converting the schedules spec to use site_prism, but it's
becoming too much for one PR so I'll continue this afterwards.

Ensure Schedule#from is six weeks in the future

---

spec/features/resource_manager_manages_groups_spec.rb

This was rebased out somehow. Derp.

Add missing spec

---

app/views/users/index.html.erb

- the markup for the glyphicon added was searchable aswell as the name

Fixing bug with searching for a guider's name

---

spec/features/resource_manager_manages_schedules_spec.rb
spec/features/roles_spec.rb
spec/features/schedules_spec.rb
spec/support/pages/edit_user.rb
spec/support/pages/layout.rb

~~Still adding site_prism so don't merge yet.~~
```
Resource manager manages groups
Viewing existing groups
Deleting a group
Resource manager manages schedules
Successfully adds a new schedule
Successfully updates a schedule
Fails to create a schedule with invalid from date
Fails to update a schedule with invalid from date
Roles
Resource Managers
Can manage guiders
Can manage guiders schedules
Can manage guiders slots
Non-resource-managers
Fail to manage guiders
Fail to manage guiders schedules
Fail to manage guiders slots
Schedule
validation
#from
is valid with valid attributes
is not nil
is a minimum of six weeks in the future
User
behaves like a gds-sso user class
implements #where
implements #update_attribute
implements #update_attributes
implements #create!
implements …
```

Refactor schedule and roles specs

---

app/models/user.rb
app/views/users/index.html.erb
db/migrate/20160930133648_create_groups_users.rb
db/schema.rb
spec/features/resource_manager_manages_guiders_spec.rb
spec/spec_helper.rb
spec/support/pages/manage_guiders.rb

Displays group membership alongside the guider details. Also adds
searchability to the groups fields for guiders.

Search and display a guider's groups

---

app/assets/stylesheets/application.scss
app/controllers/schedules_controller.rb
app/models/schedule.rb
app/views/users/edit.html.erb
spec/features/resource_manager_manages_schedules_spec.rb
spec/support/pages/edit_schedule.rb
spec/support/pages/edit_user.rb
spec/support/pages/new_schedule.rb

- Schedules can be deleted directly from the schedule list
- Schedules can NOT be deleted if they start from LESS than six weeks in
the future

Resource managers can delete schedules

---

app/models/schedule.rb
spec/features/resource_manager_manages_schedules_spec.rb
spec/models/schedule_spec.rb

~~This is WIP at the moment because I'm not sure if the UI will work properly with
the code changes.~~
Feel free to review though!

First schedule can have any #from date

---

app/models/schedule.rb
app/views/users/edit.html.erb
spec/features/resource_manager_manages_schedules_spec.rb
spec/models/schedule_spec.rb
spec/support/pages/edit_user.rb

@guntrisoft: Not sure about that `<div><strong>` going on there...

Schedules that start less than six weeks from now can't be edited

---

app/controllers/schedules_controller.rb
app/controllers/users_controller.rb
app/models/schedule.rb
app/presenters/schedule_presenter.rb
app/views/schedules/_form.html.erb
app/views/schedules/edit.html.erb
db/migrate/20161003150744_rename_schedules_from_to_start_at.rb
db/schema.rb
spec/factories/schedules.rb
spec/features/resource_manager_manages_schedules_spec.rb
spec/features/roles_spec.rb
spec/models/schedule_spec.rb
spec/support/pages/edit_schedule.rb
spec/support/pages/new_schedule.rb

To anyone looking at this, the important code is in the first commit.

Show Schedule end date (one day before next schedule start)

---

app/views/users/edit.html.erb

Reverts guidance-guarantee-programme/telephone_appointment_planner#46 as it needs a good old rebase

Revert "Correct caption for list of schedules table"

---

app/views/users/edit.html.erb

Correct caption for list of schedules table

---

app/controllers/groups_controller.rb
app/forms/create_group_assignments.rb
spec/forms/create_group_assignments_spec.rb

This doesn't need to behave like a traditional form object.

Remove unnecessary `ActiveModel::Model` mixin

---

app/controllers/groups_controller.rb

Correct flash text when group unassigned

---

app/assets/javascripts/application.js
app/assets/javascripts/calendar.es6
app/assets/javascripts/calendars/guider-slot-picker.es6

Small change but allows us to create each type of calendar as it's own separate file in future.

Extract calendar JS out to seperate files for each calendar type

---

app/assets/javascripts/calendars/guider-schedules.es6
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/guider-schedules.scss
app/models/schedule.rb
app/views/users/edit.html.erb

- shows six week window and visual indicates whether a schedule is editable or not
- altered schedule model's end_at method to take only a second off rather than a day
- improved wording of uneditable schedule sentence

Creating a graphical view of schedules

---

app/models/bookable_slot.rb

Use quoted_table_name instead of table name in SQL

---

app/views/appointments/new.html.erb

- Move mobile to first column to balance columns

Increase size of notes field on appointment/new

---

app/assets/javascripts/calendars/appointment-availability.es6
app/views/appointments/new.html.erb

Colour coded availability

---

app/controllers/appointments_controller.rb
app/views/appointments/new.html.erb
db/migrate/20161012143253_remove_year_of_birth_from_appointments.rb
db/migrate/20161012143328_add_date_of_birth_to_appointments.rb
db/schema.rb
spec/features/contact_centre_agent_creates_appointments_spec.rb
spec/support/pages/new_appointment.rb

Change appointments year_of_birth to date_of_birth

---

app/assets/javascripts/calendars/appointment-availability.es6
app/assets/stylesheets/application.scss
app/helpers/required_helper.rb
app/views/appointments/new.html.erb

Reselect slot appointments

---

app/assets/javascripts/customer-age.es6
app/assets/stylesheets/application.scss
app/controllers/appointment_attempts_controller.rb
app/views/appointment_attempts/new.html.erb
app/views/appointments/new.html.erb
app/views/shared/_date_of_birth_form_field.html.erb
spec/features/contact_centre_agent_creates_appointments_spec.rb
spec/support/pages/new_appointment_attempt.rb

- CustomerAge JS module now correctly works out the
customer's age
- Use same dob field in both places on the book appointment
form

Make DOB form element into three text fields

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/calendar.es6
app/assets/javascripts/calendars/guider-appointments.es6
app/assets/stylesheets/application.scss
app/controllers/appointments_controller.rb
app/controllers/calendars_controller.rb
app/models/user.rb
app/serializers/appointment_serializer.rb
app/views/calendars/show.html.erb
app/views/layouts/application.html.erb
config/routes.rb
spec/factories/appointments.rb
spec/features/guider_views_appointments_spec.rb
spec/support/pages/calendar.rb
spec/support/user_helpers.rb

This shows appointments scoped to the current user.
This ends at the edit appointment screen which remains to be implemented.

Guider can view their own calendar

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/views/layouts/application.html.erb

- turbolinks was causing an issue with fullcalendar
where event handling on buttons was being lost
if you hit back in the browser
- altered loading of modules in application.html.erb
adds a loaded data attribute to modules which have
been initialised

Remove turbolinks from project

---

app/views/appointment_attempts/new.html.erb
app/views/appointments/new.html.erb
app/views/shared/_date_of_birth_form_field.html.erb
app/views/shared/_required_fields_note.html.erb

- created a shared partial for the 'required field' explaination note

Adding in required field asterisks for the fields that are required

---

app/assets/stylesheets/application.scss
app/views/shared/_date_of_birth_form_field.html.erb

- the placeholder on Chrome for the month field was being cut off
so have added a width in the CSS

Fixing DOB input widths

---

app/models/user.rb

GDS-SSO provides a predicate for us to check for the presence of
permissions.

Use GDS-SSO supplied permissions check

---

spec/features/holidays_spec.rb

- altered business days to step forward to 5 from 6

Fixing holiday spec

---

app/controllers/holidays_controller.rb
app/controllers/schedules_controller.rb
app/controllers/users_controller.rb

Refactor controller authentication to use blocks where possible

---

.travis.yml
app/models/user.rb
db/migrate/20161021101029_change_user_permissions_to_json.rb
db/schema.rb
spec/models/user_spec.rb

This is much nicer and lets us query for permissions efficiently.

Use JSONB for serializing permissions

---

app/assets/javascripts/calendars/guider-appointments.es6
app/assets/stylesheets/components/_calendars.scss
app/serializers/appointment_serializer.rb

- if it's one of the two cancelled states, then it will
highlight them in red on the guider's calendar

Showing cancelled appointments on the guiders' calendar

---

spec/features/holidays_spec.rb

Many have tried, and failed.
cc @AndrewVos @Guntrisoft :poop:

Removes the time dependency from this spec

---

app/controllers/home_controller.rb
app/views/home/index.html.erb
spec/features/custom_role_redirects_spec.rb
spec/support/pages/home.rb

- agents -> appointment_attempts/new
- guiders -> calendar
- resource managers -> guiders list (this should eventually be
the resource calendar when it's been built)

Redirect home based on role

---

Gemfile
Gemfile.lock
app/assets/javascripts/calendars/holidays.es6
app/assets/stylesheets/components/_calendars.scss
app/assets/stylesheets/vendor/_vendor.scss
app/views/holidays/index.html.erb
app/views/holidays/new.html.erb
spec/support/pages/holidays.rb

- Moved new button to top left
- added breadcrumb to new holiday page
- fixed JS to make only X delete a holiday event

Improving UI for adding a new holiday

---

app/assets/javascripts/calendar.es6

Default fullcalendar firstDay to 1 (Monday) for everything

---

app/views/holidays/new.html.erb

Also delete some old unused code

Remove dateLimit from date-range-picker

---

app/assets/javascripts/calendars/guider-schedules.es6
app/assets/stylesheets/components/_guider-schedules.scss
app/views/users/edit.html.erb

- altered mentions of readonly to 'bookable'
- remove red blocks on chart - only green ones now

Simplify guider schedules chart to remove read-only concept

---

Gemfile
Gemfile.lock
app/assets/javascripts/activity-feed-poller.es6
app/assets/javascripts/application.js
app/assets/stylesheets/components/_activity-feed.scss
app/controllers/activities_controller.rb
app/controllers/application_controller.rb
app/controllers/appointments_controller.rb
app/models/activity.rb
app/models/appointment.rb
app/models/audit_activity.rb
app/models/message_activity.rb
app/models/user.rb
app/views/activities/_activity_feed.html.erb
app/views/activities/_audit_activity.html.erb
app/views/activities/_message_activity.html.erb
app/views/activities/_message_activity.js.erb
app/views/appointments/_personal_details_form.html.erb
app/views/appointments/edit.html.erb
config/routes.rb
db/migrate/20161024153420_create_activities.rb
db/migrate/20161026094415_install_audited.rb
db/schema.rb
db/seeds.rb
spec/factories/activities.rb
spec/factories/users.rb
spec/features/roles_spec.rb
spec/features/user_views_booking_activities_spec.rb
spec/models/audit_activity_spec.rb
spec/support/pages/edit_appointment.rb

It is important to note that ANY signed on user can edit an appointment now.
This is because we know who all these users are, and because the code would effectively allow any user role otherwise.

Show field update and message activities on appointments

---

Gemfile
Gemfile.lock
app/assets/javascripts/date-range-picker.es6
app/controllers/appointments_controller.rb
app/forms/search.rb
app/helpers/application_helper.rb
app/models/appointment.rb
app/presenters/appointment_presenter.rb
app/views/appointments/search.html.erb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/agent_searches_for_appointments_spec.rb
spec/models/appointment_spec.rb
spec/support/pages/search.rb

- Search on #first_name, #last_name, and #id.
- Search on a date range
- Adds pg_search
NOTE: There are no `tsvector` indexes yet!

Agents can search for appointments

---

app/views/appointments/search.html.erb

Change edit appointment button to glyphicon

---

app/views/appointments/edit.html.erb
app/views/appointments/reschedule.html.erb

- altered both to have a parent of 'search'
- this doesn't quite work 100% when you edit an appointment
coming from a guider's calendar, but will look to improve this
at another time

Altered breadcrumb for edit/reschedule appointment

---

app/models/appointment.rb
app/views/appointments/edit.html.erb
app/views/appointments/reschedule.html.erb
spec/models/appointment_spec.rb

- output the full name in breadcrumb and title to help
user know what they are edit/rescheduling

Adding method to return full name of appointment

---

app/assets/javascripts/calendars/guiders-appointments.es6
app/controllers/holidays_controller.rb
app/models/holiday.rb
app/serializers/holiday_serializer.rb
app/views/holidays/index.html.erb
config/routes.rb
spec/features/resource_manager_modifies_appointments_spec.rb
spec/models/holiday_spec.rb
spec/support/pages/resource_calendar.rb

Resource managers see holidays as background events in resource calendar

---

app/controllers/company_calendars_controller.rb
app/views/company_calendars/show.html.erb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/guider_views_appointments_spec.rb
spec/features/roles_spec.rb
spec/support/pages/company_calendar.rb

Display a calendar for guiders which shows all company appointments

---

app/assets/javascripts/calendar.es6
app/assets/javascripts/calendars/appointment-availability.es6
app/assets/javascripts/calendars/guider-appointments.es6
app/assets/javascripts/calendars/guiders-appointments.es6
app/assets/javascripts/calendars/holidays.es6
app/assets/stylesheets/components/_calendars.scss

add in jump to date button to calendars where it is relevant

---

app/assets/javascripts/calendars/appointment-availability.es6
app/controllers/appointments_controller.rb
app/models/appointment.rb
app/views/appointments/new.html.erb
app/views/appointments/reschedule.html.erb
config/routes.rb
spec/features/agent_manages_appointments_spec.rb
spec/models/appointment_spec.rb
spec/support/pages/new_appointment.rb
spec/support/pages/reschedule_appointment.rb

~WIP until pete merges all his deletions~
Also rerenders `reschedule` page when a user did not choose a slot.

Display an error when failing to assign an appointment to a guider

---

app/controllers/appointments_controller.rb
app/controllers/reports_controller.rb
app/forms/report.rb
app/models/appointment.rb
app/models/create_activity.rb
app/presenters/appointment_csv_presenter.rb
app/views/activities/_create_activity.html.erb
app/views/layouts/application.html.erb
app/views/reports/new.html.erb
config/routes.rb
db/migrate/20161101125741_add_agent_id_to_appointments.rb
db/schema.rb
spec/factories/appointments.rb
spec/features/agent_manages_appointments_spec.rb
spec/features/resource_manager_views_reports_spec.rb
spec/features/roles_spec.rb
spec/features/user_views_booking_activities_spec.rb
spec/models/appointment_spec.rb
spec/models/audit_activity_spec.rb
spec/models/create_activity_spec.rb
spec/rails_helper.rb
spec/support/pages/new_report.rb
spec/support/pages/report_csv.rb

Note that I also added the `Appointment#agent` association because it was needed in the report.

Resource managers can export appointment data as CSV

---

app/assets/javascripts/calendar.es6
app/assets/javascripts/calendars/appointment-availability.es6
app/assets/javascripts/calendars/guider-appointments.es6
app/assets/javascripts/calendars/guider-slot-picker.es6
app/assets/javascripts/calendars/guiders-appointments.es6
app/assets/javascripts/calendars/holidays.es6

- follows pattern already used with viewRender method
- instead of passing in methods as part of the defaultConfig
this moves them to methods in the class itself
- base class proxies fullcalendar event calls

Rejigged how full calendar methods are defined

---

app/controllers/appointments_controller.rb
app/mailers/application_mailer.rb
app/mailers/appointment_mailer.rb
app/views/appointment_mailer/confirmation.html.erb
app/views/appointment_mailer/confirmation.text.erb
app/views/layouts/mailer.html.erb
app/views/layouts/mailer.text.erb
config/application.rb
config/environments/production.rb
config/environments/test.rb
spec/features/agent_manages_appointments_spec.rb
spec/mailers/appointment_mailer_spec.rb
spec/mailers/previews/appointment_mailer_preview.rb
spec/rails_helper.rb

Deliver appointment confirmation email

---

spec/rails_helper.rb

Not sure how they ever really worked?

Fix broken tests

---

app/controllers/appointments_controller.rb
app/forms/batch_appointment_update.rb
app/mailers/appointment_mailer.rb
app/views/appointment_mailer/updated.html.erb
app/views/appointment_mailer/updated.text.erb
spec/factories/appointments.rb
spec/features/agent_manages_appointments_spec.rb
spec/features/resource_manager_modifies_appointments_spec.rb
spec/mailers/appointment_mailer_spec.rb
spec/mailers/previews/appointment_mailer_preview.rb
spec/rails_helper.rb

Notify customer when Agent reschedules an appointment

---

db/migrate/20161103134203_bump_appointments_id.rb
db/schema.rb

So that we don't clash with BookingBug appointments.

Start appointments id at 100,000

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/calendar.es6

- no need to install cookie gem
- use built in GOVUKAdmin template one

Use GOVUKAdmin template cookie methods

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/calendars/guider-appointments.es6
app/forms/batch_appointment_update.rb
app/jobs/pusher_notification_job.rb
app/views/calendars/show.html.erb
config/environments/test.rb
config/initializers/pusher.rb
spec/features/resource_manager_modifies_appointments_spec.rb
spec/rails_helper.rb
spec/support/pages/calendar.rb
spec/support/pages/resource_calendar.rb
spec/support/user_helpers.rb

Sends customer / guider notifications by email and pusher respectively.
For now this is only triggered when the resource manager batch updates appointments. I'll sneak around separately and ensure notifications are triggered in the correct places.
Details are in the commits. I'm going to tidy up the date formatting separately so ignore that for the time being please.

Appointment notifications

---

app/assets/javascripts/calendars/holidays.es6
app/assets/stylesheets/components/_calendars.scss
app/controllers/holidays_controller.rb
app/forms/update_holidays.rb
app/helpers/date_range_picker_helper.rb
app/jobs/generate_bank_holidays_job.rb
app/models/holiday.rb
app/serializers/holiday_serializer.rb
app/views/holidays/edit.html.erb
config/routes.rb
db/migrate/20161104112041_add_bank_holiday_to_holidays.rb
db/schema.rb
db/seeds.rb
spec/factories/holidays.rb
spec/features/resource_manager_manages_holidays_spec.rb
spec/features/resource_manager_manages_schedules_spec.rb
spec/features/resource_manager_modifies_appointments_spec.rb
spec/forms/update_holidays_spec.rb
spec/models/appointment_spec.rb
spec/models/bookable_slot_spec.rb
spec/models/holiday_spec.rb
spec/support/pages/edit_holiday.rb
spec/support/pages/edit_schedule.rb
spec/support/pages/holidays.rb
spec/support/pages/new_schedule.rb

Managers can edit/delete holidays from holiday index

---

app/assets/javascripts/date-range-picker.es6

Seems it has been broken since the govuk module PR.

Fix date-range-picker module scoping issues

---

app/controllers/appointment_reports_controller.rb
app/controllers/reports_controller.rb
app/controllers/utilisation_reports_controller.rb
app/forms/appointment_report.rb
app/forms/report.rb
app/forms/utilisation_report.rb
app/views/reports/new.html.erb
config/routes.rb
spec/factories/appointments.rb
spec/factories/bookable_slots.rb
spec/features/resource_manager_downloads_appointment_reports_spec.rb
spec/features/resource_manager_downloads_utilisation_reports_spec.rb
spec/models/bookable_slot_spec.rb
spec/models/user_spec.rb
spec/support/pages/new_report.rb

Resource managers can generate a utilisation report

---

app/assets/javascripts/calendar.es6

Rename 'Today' to 'Jump to today' for consistency

---

.eslintrc
.travis.yml
app/assets/javascripts/activity-feed-poller.es6
app/assets/javascripts/advanced-select.es6
app/assets/javascripts/calendar.es6
app/assets/javascripts/calendars/guider-slot-picker.es6
app/assets/javascripts/calendars/guiders-appointments.es6
app/assets/javascripts/customer-age.es6
app/assets/javascripts/date-range-picker.es6
app/assets/javascripts/guider-schedules-chart.es6
app/assets/javascripts/guiders-multi-action.es6
app/assets/javascripts/multi-checkbox.es6
app/assets/javascripts/sortable-list.es6
app/assets/javascripts/tap-base.es6
package.json

- realised that the root javascripts directory wasn't
being linted
- enabled some extra rules based on current style of
es6 files
- upgrade project to use node 7

Upgrade es6 lint and enable certain rules

---

app/views/appointments/search.html.erb

- the ListJS sorting only sorted the current page and not
the full set of results (which are on multiple pages)
- Removing for now, and if needed we can add in server side
sort later

Removing sorting on search as it doesn't work as expected

---

app/views/company_calendars/show.html.erb

- Highlight in yellow the column for the current guider

Highlight the current logged in guider on company calendar

---

app/models/user.rb
db/seeds.rb

Add dependent: :destroy on User#holidays
- 45   Users
- 100  Holidays
- 1000 Appointments

More realistic database seeds

---

app/views/layouts/application.html.erb

Only applies to development and staging environments.

Add bugmuncher for feedback from UAT

---

app/helpers/breadcrumb_helper.rb
app/views/appointments/edit.html.erb

I'm not sure I like the way this works. Thoughts @Guntrisoft @benlovell?

Show valid breadcrumb for edit appointments depending on referer

---

app/assets/javascripts/calendars/guider-appointments.es6
app/assets/javascripts/calendars/guiders-appointments.es6
app/controllers/bookable_slots_controller.rb
app/models/bookable_slot.rb
app/serializers/bookable_slot_serializer.rb
app/views/appointments/new.html.erb
app/views/appointments/reschedule.html.erb
app/views/calendars/show.html.erb
app/views/resource_calendars/show.html.erb
config/routes.rb
spec/features/agent_manages_appointments_spec.rb
spec/features/guider_views_appointments_spec.rb
spec/features/resource_manager_modifies_appointments_spec.rb
spec/rails_helper.rb
spec/support/pages/calendar.rb
spec/support/pages/calendar_section.rb
spec/support/pages/resource_calendar.rb

Show BookableSlots on guider appointment calendar and resource calendar

---

app/controllers/schedules_controller.rb
app/views/resource_calendars/show.html.erb
spec/features/resource_manager_manages_schedules_spec.rb

Also, change Appointments to Allocations in breadcrumb

Generate bookable slots when a guider schedule is deleted

---

app/controllers/bookable_slots_controller.rb

This speeds up slot rendering massively

Don't search six weeks of bookable slots for appointment slot picker

---

app/assets/javascripts/advanced-select.es6
app/assets/javascripts/calendars/guiders-appointments.es6
app/assets/stylesheets/components/_calendars.scss
app/helpers/user_helper.rb
app/views/resource_calendars/show.html.erb

Allow filtering on the resource calendar

---

spec/jobs/generate_bookable_slots_for_user_job_spec.rb

This should get our test coverage up quite a bit.

Add spec for GenerateBookableSlotsForUserJob

---

app/assets/javascripts/application.js
app/assets/javascripts/calendars/allocations.es6
app/assets/javascripts/calendars/company.es6
app/assets/stylesheets/components/_calendars.scss
app/views/company_calendars/show.html.erb
app/views/resource_calendars/show.html.erb
app/views/shared/_calendar_filter.html.erb

- all the methods to do with editing appointments is now
in the allocationsCalendar
- allocationCalendar extends from company calendar
- company calendar provides the basic functionality of a read
only calendar for the guiders to view the whole company
- fixes issue with filter on company calendar not working

Separate concerns of the company and resource calendars

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/calendars/company.es6
app/assets/javascripts/sortable_guiders.es6
app/controllers/users_controller.rb
app/models/user.rb
app/views/users/sort.html.erb
config/routes.rb
db/migrate/20161116103731_add_position_to_users.rb
db/schema.rb
spec/features/resource_manager_sorts_guiders_spec.rb
spec/features/roles_spec.rb
spec/support/pages/sort_guiders.rb

Resource managers can sort guiders

---

app/assets/javascripts/calendars/company.es6

Show the number of filters applied so resource managers know
that there is one applied to the current view.

Indicate filters are applied by showing on button label

---

app/assets/javascripts/calendars/allocations.es6
app/assets/stylesheets/components/_alert.scss
app/views/resource_calendars/show.html.erb

Also handles failure cases. Alerts automatically fade out after 3 seconds.

Better flash messages

---

app/controllers/appointments_controller.rb
app/views/appointments/search.html.erb
spec/features/user_rebooks_appointments_spec.rb
spec/support/pages/search.rb

Users can rebook appointments

---

app/views/activities/_activity.html.erb
spec/features/guider_views_their_activities_spec.rb
spec/features/user_views_booking_activities_spec.rb

More descriptive activity dates

---

app/assets/stylesheets/components/_calendars.scss

- altered css to work on all browsers

Fix issue with resource calendar guiders list on ie11

---

app/assets/stylesheets/components/_dob-form-field.scss
app/helpers/date_of_birth_helper.rb
app/views/shared/_date_of_birth_form_field.html.erb

fixing alignment of age in DOB field on firefox and ie11

---

app/assets/javascripts/calendar.es6
app/assets/javascripts/calendars/allocations.es6
app/assets/javascripts/calendars/guider-slot-picker.es6

- If the user makes any changes and doesn't hit the save
button then they will be alerted that they have changes
that will be lost

Stop the user from losing changes to a schedule

---

app/assets/javascripts/calendars/allocations.es6
app/assets/stylesheets/components/_calendars.scss
app/views/company_calendars/show.html.erb
app/views/resource_calendars/show.html.erb

Fullscreen resource calendar

---

app/views/appointments/edit.html.erb

adding the appointment id to the edit appointment screen

---

app/assets/javascripts/application.js
app/assets/javascripts/calendars/my-appointments.es6
app/views/my_appointments/show.html.erb

Rename guider-appointments calendar JS

---

app/assets/javascripts/calendars/allocations.es6
app/assets/javascripts/calendars/company.es6
app/assets/stylesheets/components/_calendars.scss

- in fullscreen mode on TPAS's monitors this will fit in
almost a whole day
- ensured that the row highlighter doesn't affect mouse drag

modified the height of the rows for the allocations calendar

---

app/models/appointment.rb

- Altered Completed to Complete
- Added Incomplete

Appointment status changes/addition

---

app/models/appointment.rb
app/presenters/appointment_presenter.rb
app/views/appointments/search.html.erb
spec/features/agent_searches_for_appointments_spec.rb
spec/models/appointment_spec.rb

Users can search for appointments by guider name

---

app/models/activity.rb
app/models/appointment.rb

Maybe just a slight improvement as the knowledge and responsibility for
creation of activity subclasses is moved to the base `Activity` STI
model.

Refactor towards a general-purpose audit factory

---

app/models/appointment.rb
app/views/shared/_date_of_birth_form_field.html.erb
spec/models/appointment_spec.rb

For example 31st February was being converted to 3rd May.

Validate invalid date of births

---

app/views/layouts/application.html.erb

- using body_end in gov uk admin template to insert before
close of body tag

Moving script tags which were after the close of the body

---

app/controllers/allocations_controller.rb
app/helpers/breadcrumb_helper.rb
app/views/activities/index.html.erb
app/views/allocations/show.html.erb
app/views/appointment_reports/new.html.erb
app/views/appointments/edit.html.erb
app/views/appointments/new.html.erb
app/views/appointments/reschedule.html.erb
app/views/appointments/search.html.erb
app/views/company_calendars/show.html.erb
app/views/groups/index.html.erb
app/views/holidays/edit.html.erb
app/views/holidays/index.html.erb
app/views/holidays/new.html.erb
app/views/my_appointments/show.html.erb
app/views/schedules/edit.html.erb
app/views/schedules/new.html.erb
app/views/shared/_breadcrumb.html.erb
app/views/users/edit.html.erb
app/views/users/index.html.erb
app/views/users/sort.html.erb
app/views/utilisation_reports/new.html.erb
spec/features/breadcrumb_spec.rb

- improved markup for accessibility
- reduce repetition in templates
- added 'breadcrumb for previous page' functionality for the allocations page

Turning breadcrumb into a partial and improving markup

---

app/assets/javascripts/modules/calendar.es6

- Adds label to input field that describes what it is

Improve accessibility of jump to date functionality on resource calendar

---

app/assets/javascripts/modules/customer-age.es6

**BEFORE**
**AFTER**
- If you entered letters into the text fields for DOB
it resulted in console warning errors from moment.js
- Beefed up the checking of the values for DOB to ensure
this doesn't happen

Fix bug where customer age module was throwing warnings

---

app/assets/javascripts/modules/calendar.es6
app/assets/javascripts/modules/calendars/allocations.es6
app/assets/stylesheets/components/_calendars.scss
app/controllers/holidays_controller.rb
app/views/allocations/show.html.erb
app/views/holidays/new.html.erb
config/routes.rb
spec/features/resource_manager_modifies_appointments_spec.rb
spec/rails_helper.rb
spec/support/dialog_helpers.rb
spec/support/pages/calendar_section.rb

Drag an area on the allocations calendar to add a holiday

---

app/forms/appointment_report.rb
app/forms/report.rb
app/forms/utilisation_report.rb
app/views/utilisation_reports/new.html.erb
spec/features/resource_manager_downloads_utilisation_reports_spec.rb

- Date range is now required in utilisation reports

Make the utilisation report show multiple days

---

app/forms/utilisation_report.rb
spec/features/resource_manager_downloads_utilisation_reports_spec.rb

Add missing date header in utilisation report CSV

---

Gemfile
Gemfile.lock
app/controllers/appointment_reports_controller.rb
app/controllers/utilisation_reports_controller.rb
app/models/user.rb
app/views/layouts/application.html.erb
spec/factories/users.rb
spec/features/roles_spec.rb
spec/models/user_spec.rb
spec/support/pages/activities.rb
spec/support/pages/company_calendar.rb
spec/support/pages/edit_appointment.rb
spec/support/pages/edit_schedule.rb
spec/support/pages/edit_user.rb
spec/support/pages/holidays.rb
spec/support/pages/new_appointment.rb
spec/support/pages/new_appointment_report.rb
spec/support/pages/new_utilisation_report.rb
spec/support/pages/reschedule_appointment.rb
spec/support/pages/sort_guiders.rb
spec/support/pages/users.rb
spec/support/user_helpers.rb

Introduces team leaders and grants them access to the reporting
functionality.
Depends on unreleased changes to GDS-SSO: alphagov/gds-sso#112

Grant team leaders access to reporting

---

Gemfile
Gemfile.lock
config/newrelic.yml

Let's track and intrument performance metrics as we do with planner and
our other applications.

Add newrelic instrumentation

---

app/assets/stylesheets/components/_appointment_search.scss
app/views/appointments/search.html.erb

**Before**
**After**
- making the form inline, so it fits on one row

Improve layout of search form to bring results higher up the page

---

.eslintrc
app/assets/javascripts/modules/calendars/guider-slot-picker.es6
package.json

- altered eslint command line to correctly look for any
.es6 files within the javascripts directory

Adding no-params-reassign option to eslint

---

app/assets/javascripts/modules/calendars/appointment-availability.es6

- To ensure consistency across JS modules

Ensure that init() method is straight after start() in all modules

---

app/assets/javascripts/modules/search-highlight.es6
app/models/appointment_search.rb
spec/models/appointment_search_spec.rb

Match on multiple words in appointment search

---

app/assets/javascripts/modules/activity-feed.es6
app/views/activities/_activity.html.erb

Stray socket connections were afoot.
These needed to get oot.
Time to pocket the unwanted sockets.
🚀

Prevent activity feed duplicates and stray websocket connections

---

app/lib/notifier.rb
app/mailers/appointment_mailer.rb
app/views/appointment_mailer/cancelled.html.erb
app/views/appointment_mailer/cancelled.text.erb
spec/features/agent_manages_appointments_spec.rb
spec/mailers/appointment_mailer_spec.rb
spec/mailers/previews/appointment_mailer_preview.rb

~~Do not merge until @benbarnett has adjusted the content for this.~~

Email customer when appointment is cancelled by them or PensionWise

---

app/lib/notifier.rb
app/mailers/appointment_mailer.rb
app/models/appointment.rb
app/views/appointment_mailer/missed.html.erb
app/views/appointment_mailer/missed.text.erb
spec/features/agent_manages_appointments_spec.rb
spec/mailers/appointment_mailer_spec.rb
spec/mailers/previews/appointment_mailer_preview.rb

Email the customer when they miss an appointment

---

app/views/appointment_mailer/confirmation.html.erb
app/views/appointment_mailer/confirmation.text.erb
spec/mailers/appointment_mailer_spec.rb

Correct confirmation email copy

---

app/models/appointment.rb
app/views/appointments/edit.html.erb
app/views/appointments/search.html.erb
spec/models/appointment_spec.rb

Not sure I like how this looks. Maybe I should output a disabled button instead?

Guiders can't reschedule appointment within 2 days, resource managers can

---

app/views/appointments/edit.html.erb
app/views/appointments/search.html.erb

Change 'Rebook' icon to more of a repeat symbol

---

app/controllers/guiders_controller.rb
app/controllers/users_controller.rb
app/helpers/user_helper.rb
app/models/bookable_slot.rb
app/models/user.rb
app/views/company_calendars/show.html.erb
app/views/users/index.html.erb
config/routes.rb
db/migrate/20161202164324_add_active_to_users.rb
db/schema.rb
spec/factories/users.rb
spec/features/guider_views_appointments_spec.rb
spec/features/resource_manager_manages_guiders_spec.rb
spec/features/resource_manager_sorts_guiders_spec.rb
spec/features/roles_spec.rb
spec/support/pages/company_calendar.rb
spec/support/pages/manage_guiders.rb
spec/support/pages/users.rb
spec/support/sections/calendar.rb

Guiders can be deactivated

---

app/views/users/index.html.erb
config/locales/en.yml

Also shows the 'activate' (play) button in the success colour
to stand out a little more.
Before:
After:

Explain activate/deactivate guider actions in more detail

---

app/forms/batch_upsert_holidays.rb
spec/forms/batch_upsert_holidays_spec.rb

It should be the end of the last day.

Fix bug where all day holidays end_at is the start of the last day

---

app/views/appointments/edit.html.erb
spec/factories/appointments.rb
spec/features/agent_manages_appointments_spec.rb
spec/support/pages/edit_appointment.rb

Warn about imported appointments on the edit page

---

app/controllers/appointments_controller.rb
app/views/appointments/new.html.erb
app/views/appointments/preview.html.erb
config/routes.rb
spec/features/agent_manages_appointments_spec.rb
spec/support/pages/new_appointment.rb
spec/support/pages/preview_appointment.rb

~~@benbarnett Not sure about that copy, so keeping in `[draft]` for now.~~
~~This is my third approach at doing this. The other two were quite ugly and used javascript :cry:~~
~~I'm sure there are some nice refactorings that could be done so I'm taking a look at that now. Feel free to review it now though.~~

Agents see an appointment preview before they can confirm

---

spec/features/agent_manages_appointments_spec.rb

The date is sometimes other days too.

Fix test that relied on the date always being 7th December 2016

---

app/forms/appointment_report.rb

This speeds up the reporting for appointments significantly, when faced
with a large data set.
Also took an opportunity to make some small refactoring improvements to
the style / structure.

Preload appointment relations

---

app/helpers/user_helper.rb

This was causing a huge N+1 query through groups / assignments / users.

Reduce huge N+1 querying for associated user IDs

---

app/controllers/guiders_controller.rb

This is trivially cacheable stuff. Once loaded the response times are
cut down to ~2ms on my machine.

Cache guiders JSON responses

---

app/models/bookable_slot.rb
spec/models/bookable_slot_spec.rb

Also, the test names now read better.

Slots with holidays that have same start+end are excluded

---

Gemfile
Gemfile.lock
spec/features/resource_manager_modifies_appointments_spec.rb
spec/spec_helper.rb

A temporary fix so that we have more stable builds.

Retry flaky tests three times

---

spec/features/resource_manager_manages_holidays_spec.rb

I'll address these real soon now (tm).

Add another flakey one to the retry list

---

Gemfile.lock

- https://github.com/pusher/pusher-js/releases for more info

Update pusher to latest version (4.0.0)

---

Gemfile.lock

- 1.2.0 -> 1.3.0
- change history here: https://github.com/javve/list.js/blob/master/History.md

Update listjs to latest version

---

app/forms/appointment_report.rb

This may help a little with memory consumption when generating the
appointment report.

Iterate the appointments in batches

---

app/jobs/appointment_reminder_job.rb
app/models/assignment_activity.rb
app/models/create_activity.rb
app/views/activities/_activity.html.erb
app/views/activities/_assignment_activity.html.erb
app/views/activities/_audit_activity.html.erb
app/views/activities/_create_activity.html.erb
app/views/activities/_drop_activity.html.erb
app/views/activities/_message_activity.html.erb
app/views/activities/_reminder_activity.html.erb
db/migrate/20161221152514_set_activities_message_default.rb
db/schema.rb
spec/features/guider_views_their_activities_spec.rb
spec/models/assignment_activity_spec.rb
spec/models/create_activity_spec.rb

Also, add icons for each activity.

Change activity copy to use proper sentences

---

app/views/allocations/show.html.erb
app/views/appointments/_availability_calendar.html.erb
app/views/company_calendars/show.html.erb
app/views/holidays/index.html.erb
app/views/schedules/_form.html.erb
app/views/shared/_nojs.html.erb
app/views/users/index.html.erb
app/views/users/sort.html.erb

- hiding search and selection form elements from nojs browsers
- adding enable JS message for nojs browsers across various pages

Adding a no-js message

---

app/assets/javascripts/modules/form-change-monitor.es6
app/views/appointments/edit.html.erb

- Alert user about unsaved changes when trying to leave
the edit appointment page

Add check for unsaved changes when editing an appointment

---

app/assets/javascripts/modules/calendars/company.es6
spec/features/resource_manager_modifies_appointments_spec.rb

- added to company and allocations calendar

Open appointments in new tab to avoid losing position in calendar

---

spec/features/guider_views_appointments_spec.rb
spec/features/guider_views_their_activities_spec.rb
spec/features/roles_spec.rb

There were a few places where things were fat-fingered.

Correct some typos I found in the specs

---

db/seeds.rb

To make development testing slightly easier

Seed first user with Pension Wise API user

---

app/views/appointment_mailer/cancelled.html.erb
app/views/appointment_mailer/cancelled.text.erb
app/views/appointment_mailer/confirmation.html.erb
app/views/appointment_mailer/confirmation.text.erb
app/views/appointment_mailer/missed.html.erb
app/views/appointment_mailer/missed.text.erb
app/views/appointment_mailer/reminder.html.erb
app/views/appointment_mailer/reminder.text.erb
app/views/appointment_mailer/updated.html.erb
app/views/appointment_mailer/updated.text.erb

- Altered 'Start time' to 'Time'
- Remove name of guider from cancellation email

Improve consistency of email layouts

---

Gemfile
Gemfile.lock
app/jobs/slack_pinger_job.rb
app/lib/web_hook.rb
spec/lib/web_hook_spec.rb
spec/support/webmock.rb

Will ping slack on a schedule with the last hour's count of
appointments. When `0` we don't post anything as there's no real point.

Ping slack with the last hour's appointment count

---

app/models/customer_update_activity.rb

Fix typo in CustomerUpdateActivity::UPDATED_MESSAGE

---

app/models/appointment.rb
app/models/bookable_slot.rb
spec/models/appointment_spec.rb

Reverts guidance-guarantee-programme/telephone_appointment_planner#495
We may have jumped the gun a little on this one. Reverting until we can fully understand the issue with TPAS.

Revert "Calculate grace period from close of play"

---

Gemfile
Gemfile.lock

This was annoying me beyond belief.

Remove `Fixnum` deprecation messages

---

db/migrate/20170413091442_resolve_existing_activities.rb
db/schema.rb

Now we correctly assign responsibility for these it makes sense to mark
the existing activities as resolved so the agents and guiders have a
clean break.

Resolve outstanding high-priority activities

---

app/assets/javascripts/modules/calendar.es6
app/assets/javascripts/modules/calendars/appointment-availability.es6
app/assets/javascripts/modules/calendars/company.es6
app/assets/stylesheets/components/_calendars.scss
app/controllers/bookable_slots_controller.rb
app/views/shared/_calendar_filter.html.erb

Show schedule while on holiday

---

app/assets/javascripts/modules/calendar.es6
app/assets/javascripts/modules/calendars/appointment-availability.es6
app/assets/javascripts/modules/calendars/company.es6
app/assets/stylesheets/components/_calendars.scss
app/controllers/bookable_slots_controller.rb
app/views/shared/_calendar_filter.html.erb

Reverts guidance-guarantee-programme/telephone_appointment_planner#515
This needs some work on the 'between' logic.

Revert "Show schedule while on holiday"

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/mailgun-validator.js
app/assets/javascripts/modules/calendar.es6
app/assets/javascripts/modules/email-validator.es6
app/assets/stylesheets/components/_button-link.scss
app/assets/stylesheets/components/_email-suggestion-loading.scss
app/assets/stylesheets/components/_form-group.scss
app/assets/stylesheets/components/_loading-spinner.scss
app/views/appointments/_personal_details_form.html.erb
spec/features/appointment_email_address_suggestion_spec.rb
spec/support/pages/new_appointment.rb

Almost ready for review, with a few things remaining before removing the WIP status:
* ~~Assistance requested from @Guntrisoft to adjust the size of the spinner and verify the choice of class name and sass placement~~.
* ~~Assistance requested from @Guntrisoft to also switch out the link with an appropriately styled button~~.
* ~~Input requested from @benlovell as to handing of the api key - naming of the environment variable and usage of a default key when not present (the one there's been borrowed from a Mailgun account of mine)~~.

Validate appointment email addresses with Mailgun

---

Gemfile
Gemfile.lock

Brings us up to date with Rails and other bundled dependencies.

Updates dependencies

---

app/models/bookable_slot.rb
spec/requests/bookable_slots_api_spec.rb

Increasing the booking window from 6 weeks to 8 weeks due to
availability at TPAS.

Increase booking window to 8 weeks

---

app/controllers/bookable_slots_controller.rb
app/models/appointment.rb
app/models/bookable_slot.rb
spec/models/appointment_spec.rb

Ensures guider conference days are not bookable.

Exclude guider conference days

---

app/controllers/application_controller.rb
config/environments/production.rb

Ensures this is included in our structured logs.

Log remote IP addresses

---

app/models/appointment.rb
app/views/appointments/edit.html.erb

List any appointment duplicated by start date and customer name.

Add a basic check for duplicates

---

app/models/appointment.rb
spec/models/appointment_spec.rb

Addresses issues with correction of customer or agent-supplied data after
creation.

A few minor bug fixes

---

app/assets/javascripts/modules/calendar.es6
app/models/appointment.rb
app/models/bookable_slot.rb
app/presenters/appointment_search_result_presenter.rb
app/views/activities/_activity.html.erb
app/views/appointments/edit.html.erb
spec/features/guider_edits_an_appointment_spec.rb
spec/models/appointment_spec.rb
spec/models/bookable_slot_spec.rb

This is hacky as hell but once merged will revert to the GMT timezone
correctly.
When I get a chance I will add proper timezone support. I promise.

Revert changes required to accomodate TZ change

---

.travis.yml
package.json
spec/lib/notifier_spec.rb

This was complaining about new config syntax during CI builds.

Pin `eslint` dependency

---

app/assets/javascripts/modules/date-time-picker.es6

This was previously misconfigured.

Correctly disable weekends

---

app/views/shared/email/_preparing_for_appointment.html.erb
app/views/shared/email/_preparing_for_appointment.text.erb

Update number for the future pension centre

---

app/lib/where_you_heard.rb

In readiness for a new campaign.

Additional WDYH option

---

Gemfile
Gemfile.lock
config/boot.rb

Speeds up load times when booting up for tests and other uses.

Add bootsnap configuration for quick boots

---

app/assets/javascripts/modules/calendar.es6
app/models/appointment.rb
app/models/bookable_slot.rb
app/presenters/appointment_search_result_presenter.rb
app/views/activities/_activity.html.erb
app/views/appointments/edit.html.erb
spec/features/guider_edits_an_appointment_spec.rb
spec/models/appointment_spec.rb
spec/models/bookable_slot_spec.rb

Ensures we can accomodate the BST timezone change due later this month.
This should be merged and deployed by 1AM 25/03/18.

Accomodate BST timezone

---

app/views/shared/email/_preparing_for_appointment.html.erb
app/views/shared/email/_preparing_for_appointment.text.erb

Clarifies some of this content with regards to preparing for your
appointment.

Improve confirmation/reminder email content

---

Gemfile.lock
spec/features/agent_searches_for_appointments_spec.rb
spec/models/appointment_search_spec.rb

These specs are borked by the guider conference day restrictions.

Fix time-sensitive specs

---

app/controllers/bookable_slots_controller.rb
app/models/appointment.rb
app/models/bookable_slot.rb
spec/models/appointment_spec.rb

These are no longer necessary so can be removed.

Remove guider conference checks

---

app/models/user.rb
app/presenters/appointment_search_result_presenter.rb
app/views/appointments/search.html.erb
spec/models/user_spec.rb

Displays the organisation in the search index results.

Display the guider's organisation

---

app/views/appointments/_personal_details_form.html.erb

This is now deemed unnecessary.

Remove Ipsos MORI help block

---

app/assets/javascripts/modules/calendar.es6
app/models/appointment.rb
app/models/bookable_slot.rb
app/presenters/appointment_search_result_presenter.rb
app/views/activities/_activity.html.erb
app/views/appointments/edit.html.erb
spec/features/guider_edits_an_appointment_spec.rb
spec/models/appointment_spec.rb
spec/models/bookable_slot_spec.rb

Super hacky hack to handle the upcoming timezone change.

Allow for timezone change

---

app/views/layouts/application.html.erb
spec/features/resource_manager_manages_schedules_spec.rb

We are having issues with deliverability to btinternet.com email
addresses.

Add temporary email notice

---

app/views/layouts/application.html.erb
spec/features/resource_manager_manages_schedules_spec.rb

Reverts guidance-guarantee-programme/telephone_appointment_planner#621

Revert "Add temporary email notice"

---

app/helpers/user_helper.rb
app/lib/scheduled_reporting_summary.rb
app/models/user.rb
spec/factories/bookable_slots.rb
spec/factories/users.rb
spec/features/scheduled_reporting_summary_spec.rb

NI will be offering telephony appointments so they'll need to be
configured as a provider.

Add NI as a telephony provider

---

app/assets/javascripts/modules/calendar.es6
app/models/appointment.rb
app/models/bookable_slot.rb
app/presenters/appointment_search_result_presenter.rb
app/views/activities/_activity.html.erb
app/views/appointments/edit.html.erb
spec/features/guider_edits_an_appointment_spec.rb
spec/models/appointment_spec.rb
spec/models/bookable_slot_spec.rb

Super hacky-hack time to handle the timezone change this weekend.
This reverts commit e948e168b78db45f8e6757bc7067fcc83591ad80.

Revert "Allow for timezone change"

---

app/controllers/application_controller.rb
config/environments/production.rb

This should make ownership easier to determine when something untoward
happens.

Tag logs with the current user ID

---

lib/tasks/confidentiality.rake

Redacts a customer's personal details and removes any associated audits
or activities which would also expose any personal information.

Redact customer details on request

---

app/models/user.rb
spec/factories/bookable_slots.rb
spec/factories/users.rb
spec/features/scheduled_reporting_summary_spec.rb

Adds the new CITA Wallsend provider, they have the same general
permissions as the other providers.

Add CITA Wallsend provider

---

app/views/schedules/_form.html.erb

This renames existing templates and adds a new template for the 'late'
shift as requested by TPAS for their seasonal guider allocations.

Modifies the scheduling templates

---

app/models/bookable_slot.rb
spec/requests/bookable_slots_api_spec.rb

Reduces the grace period to one day across all providers per a request
from TPAS.

Reduce grace period to effectively one day

---

app/views/shared/email/_preparing_for_appointment.html.erb
app/views/shared/email/_preparing_for_appointment.text.erb

Adds useful signposting for customers.

Add COVID-19 information to customer mails

---

app/jobs/appointment_cancelled_notifications_job.rb
app/jobs/appointment_created_notifications_job.rb
app/jobs/appointment_rescheduled_notifications_job.rb
app/models/appointment.rb
app/models/user.rb
spec/jobs/appointment_cancelled_notifications_job_spec.rb
spec/jobs/appointment_created_notifications_job_spec.rb
spec/jobs/appointment_rescheduled_notifications_job_spec.rb

They don't find these alerts useful.

Don't email alert NI resource managers

---

app/models/bookable_slot.rb
spec/features/scheduled_reporting_summary_spec.rb
spec/requests/bookable_slots_api_spec.rb

This reverts commit 497049725556533ae285ebefc2a819eecaf146fb.

Revert "Temporarily exclude CAS slots from API respinse"

---

app/models/bookable_slot.rb
spec/requests/bookable_slots_api_spec.rb

This will help with reallocation efforts during the health crisis.

Increase TPAS grace period to 5 days

---

app/controllers/holidays_controller.rb
app/models/holiday.rb
spec/models/holiday_spec.rb

This was previously returning all holidays for a given organisation.

Ensure merged holidays are date ranged

---

app/controllers/appointments_controller.rb

Temporary fix while I determine the real issue.

Temporarily address rescheduling

---

app/models/bookable_slot.rb
spec/requests/bookable_slots_api_spec.rb

Bump TPAS-specific grace period to 48 hours

---

app/controllers/application_controller.rb
app/controllers/users_controller.rb
app/helpers/user_helper.rb
app/models/provider.rb
app/models/user.rb
app/views/layouts/application.html.erb
spec/factories/users.rb
spec/features/roles_spec.rb
spec/support/user_helpers.rb

Allows CITA (or other) business analysts to switch their
provider/organisation.

Allow Business Analysts to set organisation

---

app/models/bookable_slot.rb
spec/requests/bookable_slots_api_spec.rb

Reduce grace period to 24 hours effectively

---

Gemfile
Gemfile.lock
lib/tasks/export.rake

This data gets exported to blob storage as CSVs for mining.

Export data to blob storage

---

app/jobs/appointment_cancelled_notifications_job.rb
app/jobs/appointment_created_notifications_job.rb
app/jobs/appointment_rescheduled_notifications_job.rb
app/models/user.rb
spec/jobs/appointment_cancelled_notifications_job_spec.rb
spec/jobs/appointment_created_notifications_job_spec.rb
spec/jobs/appointment_rescheduled_notifications_job_spec.rb

Except those listed in the exclusions list.

Send alerts to NI resource managers

---

Gemfile
Gemfile.lock
app/models/appointment.rb
lib/tasks/surnames.rake
spec/models/appointment_spec.rb

Using the rails helpers for this was a bad idea in the first place.

Correctly capitalise surnames

---

app/assets/javascripts/modules/calendars/guider-slot-picker.es6
app/views/schedules/_form.html.erb

Slot templates can now specify a particular day they pertain to.

Alter the slot templates for TPAS

---

app/views/schedules/_form.html.erb

These times were incorrectly supplied the first time around.

Correct slot templates

---

app/views/appointment_mailer/consent_form.html.erb
app/views/appointment_mailer/consent_form.text.erb
app/views/consents/create.html.erb

This is while routing issues for this mailbox are being resolved.

Temporarily replace the contact@ mailbox address

---

app/views/appointment_mailer/consent_form.html.erb
app/views/appointment_mailer/consent_form.text.erb
app/views/consents/create.html.erb

Reverts guidance-guarantee-programme/telephone_appointment_planner#749

Revert "Temporarily replace the contact@ mailbox address"

---

app/models/bookable_slot.rb
spec/models/bookable_slot_spec.rb
spec/requests/bookable_slots_api_spec.rb

Add a further 24 hours to the grace period

---

app/controllers/appointments_controller.rb
app/lib/notifier.rb
spec/lib/notifier_spec.rb

Adds further notification hooks for both customers and resource managers.

Notifications

---

app/models/bookable_slot.rb
spec/models/bookable_slot_spec.rb
spec/requests/bookable_slots_api_spec.rb

TPAS have effectively 3 days grace period and other providers have
effectively 1 day grace period.

Permit a longer grace period for TPAS

---

app/controllers/api/v1/appointments_controller.rb
app/controllers/api/v1/bookable_slots_controller.rb
app/forms/api/v1/appointment.rb
app/models/provider.rb
app/views/appointments/_personal_details_form.html.erb
app/views/appointments/edit.html.erb
db/migrate/20210324144158_add_lloyds_signposted_to_appointments.rb
db/schema.rb
spec/forms/api/v1/appointment_spec.rb
spec/requests/appointments_api_spec.rb
spec/requests/bookable_slots_api_spec.rb

Adds filtering and flagging for Lloyds appointments.

Lloyds signposting

---

app/controllers/appointments_controller.rb
app/views/appointments/search.html.erb
spec/features/agent_searches_for_appointments_spec.rb
spec/forms/api/v1/appointment_spec.rb
spec/support/pages/search.rb

Displays a script to read to the customer once an appointment is placed,
to inform them about the upcoming changes to Money Helper.

Display modal for TP agents

---

app/assets/javascripts/modules/secondary-status.es6
app/controllers/appointments_controller.rb
app/models/appointment.rb
app/presenters/audit_presenter.rb
app/views/appointments/_personal_details_form.html.erb
db/migrate/20210428095627_add_secondary_status_to_appointments.rb
db/schema.rb
spec/features/agent_manages_appointments_spec.rb
spec/features/agent_rebooks_appointments_spec.rb
spec/features/appointment_changes_spec.rb
spec/features/resource_manager_downloads_utilisation_reports_spec.rb
spec/features/resource_manager_reschedules_an_appointment_spec.rb
spec/models/appointment_spec.rb
spec/models/bookable_slot_spec.rb
spec/support/pages/edit_appointment.rb

Certain statuses when selected now trigger a mandatory secondary status to
provide further insights.

Secondary statuses

---

app/controllers/appointments_controller.rb
app/views/appointments/search.html.erb
spec/features/agent_searches_for_appointments_spec.rb
spec/support/pages/search.rb

Remove MoneyHelper modal script

---

app/views/shared/email/_appointment_details.html.erb
app/views/shared/email/_appointment_details.text.erb

This is to attempt to discourage customers from sending email requests
for these particular tasks.

Update email wording

---

Gemfile
Gemfile.lock
app/models/bookable_slot.rb
spec/requests/bookable_slots_api_spec.rb

This reverts commit de08ddbf85c60a0e85526016a98491dbbde577fd.

Revert "Permit a longer grace period for TPAS"

---

app/assets/javascripts/modules/calendar.es6
app/models/appointment.rb
app/models/bookable_slot.rb
app/presenters/appointment_search_result_presenter.rb
app/views/activities/_activity.html.erb
app/views/appointments/edit.html.erb
spec/features/guider_edits_an_appointment_spec.rb
spec/models/appointment_spec.rb
spec/models/bookable_slot_spec.rb

Reverts guidance-guarantee-programme/telephone_appointment_planner#765

Revert "Revert "Allow for timezone change""

---

app/controllers/appointment_reports_controller.rb
app/controllers/utilisation_reports_controller.rb
app/forms/appointment_report.rb
app/forms/utilisation_report.rb
app/views/appointment_reports/new.html.erb
app/views/utilisation_reports/new.html.erb
spec/features/resource_manager_downloads_appointment_reports_spec.rb
spec/features/resource_manager_downloads_utilisation_reports_spec.rb
spec/support/pages/new_appointment_report.rb
spec/support/pages/new_utilisation_report.rb

Allows segmentation for reports based on the user's organisational membership.

Segmented reports

---

app/assets/javascripts/modules/calendars/my-appointments.es6

PSG appointments ought to be highlighted on personal calendars too.

Highlight PSG appointments

---

app/views/appointment_mailer/confirmation.html.erb
app/views/appointment_mailer/confirmation.text.erb
app/views/appointment_mailer/reminder.html.erb
app/views/appointment_mailer/reminder.text.erb
app/views/appointment_mailer/updated.html.erb
app/views/appointment_mailer/updated.text.erb
app/views/shared/email/_money_helper.html.erb
app/views/shared/email/_money_helper.text.erb
spec/mailers/appointment_mailer_spec.rb

Replaces the MH disclaimer with the latest approved version.

Replace MoneyHelper disclaimer

---

app/controllers/email_confirmations_controller.rb
app/models/appointment.rb
app/views/appointments/edit.html.erb
config/routes.rb
spec/features/guider_edits_an_appointment_spec.rb
spec/support/pages/edit_appointment.rb

Allows agents to resend email confirmations when requested to by customers.

Allow TP agents to resend email confirmations

---

Gemfile
Gemfile.lock
spec/rails_helper.rb

Remove coveralls

---

Gemfile
Gemfile.lock
spec/support/chrome.rb

This ought to be a bit more workable when chrome is updated.

Bump webdrivers and configure

---

app/views/schedules/_form.html.erb
spec/features/resource_manager_manages_schedules_spec.rb

This regressed from the appointment search change.

Ensure schedule date is formatted correctly

---

.travis.yml
package-lock.json
package.json

Also bumps puppeteer/browsers for compatibility.

Bump chromedriver for CI

---

app/models/appointment.rb
spec/features/agent_manages_appointments_spec.rb
spec/models/appointment_spec.rb

The cut-off has been changed to apply only to this status.

Add secondary statuses for 'no show'

---

app/helpers/appointment_helper.rb
app/models/appointment.rb
app/models/provider.rb
app/models/user.rb
app/views/appointments/_personal_details_form.html.erb
spec/features/agent_manages_appointments_spec.rb
spec/models/appointment_spec.rb

For now, these are the only users to maintain this particular attribute.

Restrict Welsh option to Cardiff and Vale

---

app/presenters/duplicate_presenter.rb

This can occur in some older appointments.

Handle unresolvable providers

---

app/models/appointment.rb

The field is only visible to those that are permitted to manage it.

Only validate this upon creation

---

app/views/shared/email/_appointment_details.html.erb
app/views/shared/email/_appointment_details.text.erb

This is to try and move people away from cancelling by telephone.

Change cancellation hints

---

app/views/shared/email/_appointment_details.html.erb
app/views/shared/email/_appointment_details.text.erb

This reverts commit ef91bd1409a5acb049b668e7803be92304eea83a.

Revert "Change cancellation hints"

---

app/lib/scheduled_reporting_summary.rb
db/migrate/20240925124623_add_last_available_slot_on_to_reporting_summaries.rb
db/schema.rb
spec/features/scheduled_reporting_summary_spec.rb

Adds to the existing reporting table in order for us to easily report on these with Blazer.

Report last available slot

---

app/lib/scheduled_reporting_summary.rb
db/migrate/20240925133422_add_last_slot_on_to_reporting_summaries.rb
db/schema.rb
spec/features/scheduled_reporting_summary_spec.rb

This will include the last slot date whether it's booked on or not.

Add last actual slot to reporting summary

---

app/jobs/generate_bookable_slots_job.rb
app/models/appointment.rb
app/models/bookable_slot.rb
app/views/users/index.html.erb
db/seeds.rb
spec/features/agent_manages_appointments_spec.rb
spec/features/resource_manager_manages_guiders_spec.rb
spec/requests/bookable_slots_api_spec.rb

This is for parity with the rest of the service.

Reduce window down to 8 weeks from 11

---

app/assets/javascripts/modules/calendars/allocations.es6
app/controllers/appointments_controller.rb
app/lib/batch_appointment_update.rb
app/models/appointment.rb
app/views/allocations/show.html.erb
app/views/appointments/reschedule.html.erb
db/migrate/20240925185317_add_rescheduling_route_to_appointments.rb
db/schema.rb
spec/features/agent_manages_appointments_spec.rb
spec/features/booking_due_diligence_appointments_spec.rb
spec/features/resource_manager_modifies_appointments_spec.rb
spec/features/resource_manager_reschedules_an_appointment_spec.rb
spec/support/pages/allocations.rb
spec/support/pages/reschedule_appointment.rb

The agent must choose the route the customer took to reschedule when they specify client rescheduling.

Add rescheduling route

---

app/assets/javascripts/modules/calendar.es6
app/models/appointment.rb
app/presenters/appointment_search_result_presenter.rb
app/views/activities/_activity.html.erb
app/views/appointments/edit.html.erb
spec/features/guider_edits_an_appointment_spec.rb
spec/models/appointment_spec.rb
spec/models/bookable_slot_spec.rb

Reverts guidance-guarantee-programme/telephone_appointment_planner#936

Revert DST

---

app/models/bookable_slot.rb

Reverts guidance-guarantee-programme/telephone_appointment_planner#1012

Revert "Range the holidays when possible"

---

db/migrate/20241215171846_add_appointments_index_for_slots_optimisations.rb
db/schema.rb

This vastly improves the query plan for the backend slots API call.

Add index to cover slots access for appointments

---

app/views/shared/email/_preparing_for_appointment.html.erb
app/views/shared/email/_preparing_for_appointment.text.erb
spec/mailers/appointment_mailer_spec.rb

These improvements were from feedback received from customers and ops agents/guiders.

Improve PSG preparation text

---

app/lib/scheduled_reporting_summary.rb
db/migrate/20250227135211_add_schedule_type_to_reporting_summaries.rb
db/schema.rb
lib/tasks/export.rake
spec/features/scheduled_reporting_summary_spec.rb

These include a new split to cover individual schedule types.

Include extra data fields for reporting summaries
